<?php $this->headScript()->appendFile('/js/modules/recovery.js') ?> 
<?php if(isset($this->changed)): ?>
    <div class="alert alert-success">
        <button class="close" data-dismiss="alert"></button>
        La contraseña se ha modificado correctamente.
    </div>  
<?php else: ?>	
	<?php if(count($this->errors)>0):?>		
		<div id="divpErrorLogin" class="alert alert-error" style="display:block;">
		  <button type="button" class="close" data-dismiss="alert">×</button>
		  <h4>Error</h4>
		  <?php if(@$this->errors['noPerm']==1):?>
			<div>La contraseña actual es incorrecta,favor de verificarla.</div>
		  <?php endif;?>
		  <?php if(@$this->errors['noupdate']==1):?>
			<div>Ocurrio un error al actualizar la contraseña, favor de intentar mas tarde.</div>
		  <?php endif;?>		  
		</div>	 
	<?php endif;?>
	<form method="POST" action="/main/main/recovery" id="FormData" class="form-horizontal ">
		<input type="hidden" name="onaction" value="submit" />
		<fieldset>		                    
			<div class="control-group">
				<label class="control-label">Contraseña Actual<span class="required">*</span></label>
				<div class="controls">
					<input type="password" name="inputPassword" data-required="1" class="span6 m-wrap" value="<?php echo (@$this->data['inputPassword']); ?>">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Nueva Contraseña<span class="required">*</span></label>
				<div class="controls">
					<input id="inputNewPass" name="inputNewPass" type="password" class="span6 m-wrap" value="<?php echo (@$this->data['inputNewPass']); ?>">
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Confirmar Contraseña<span class="required">*</span></label>
				<div class="controls">
					<input name="inputRepPass" type="password" class="span6 m-wrap" value="<?php echo (@$this->data['inputRepPass']); ?>">
				</div>
			</div>	
	    	<div class="col-xs-4 col-md-5">
				<div class="pull-right">			
					<button type="submit" class="btn btn-default bg-btn-send">Enviar</button>
				</div>    
	    	</div>					
		</fieldset>
	</form>
<?php endif; ?>	
