<?php $this->headScript()->appendFile('/js/main/searchActivos.js') ?>  	
    <!-- block -->
    <div class="block">
        <div class="block-content collapse in">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                    <thead>
                        <tr>
                        	<th>Modelo</th>
                            <th>Marca</th>
                            <th>Descripción</th>
                            <th>Placas</th>
                            <th>Serie</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>                                
                        <?php foreach($this->dataTable as $key => $items): ?>  
                        <tr class="odd gradeX">
                            <td><?php echo $items['MODELO']; ?></td>
                            <td><?php echo $items['MARCA']; ?></td>
                            <td><?php echo $items['DESCRIPCION']; ?></td>
                            <td><?php echo $items['PLACAS']; ?></td>
                            <td><?php echo $items['SERIE']; ?></td>
                            <td class="text-center">                                
                                <a href="javascript:parent.assignValue('<?php echo $items['DESCRIPCION']."-".$items['PLACAS']; ?>',<?php echo $items['ID_ACTIVO'];?>)"><button class="btn btn-primary"> <i class="icon-circle-arrow-down icon-white"></i></button></a>
                            </td>
                        </tr>    
                        <?php endforeach;?>                                             
                    </tbody>
                </table>
        </div>
    </div>
    <!-- /block -->