<?php $this->headScript()->appendFile('/js/modules/general/jGeneralSearch.js') ?>	
<?php //$this->headScript()->appendFile('/js/modules/gralTables.js') ?>   
<div class="block">
    <div class="block-content collapse in">
        <table class="table table-striped table-hover table-bordered">
            <thead>             
                <tr>
                    <th>Folio Cita</th>
                    <th>Tipo Servicio</th>
                    <th>Estatus</th>
                    <th>Cliente</th>
                    <th>Fecha Programada</th>
                    <th>Hora Programada</th>
                    <th>Técnico Asignado</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->dataSearch as $key => $items): ?>
                    <tr>                   
                        <td><?php echo $items['FOLIO'];?></td>
                        <td><?php echo $items['N_TIPO'];?></td>
                        <td><?php echo $items['DESCRIPCION'];?></td>
                        <td><?php echo $items['NOMBRE_CLIENTE'];?></td>
                        <td><?php echo $items['F_PROGRAMADA'];?></td>
                        <td><?php echo $items['H_PROGRAMADA'];?></td>                                    
                        <td><?php echo $items['NOMBRE_TECNICO'];?></td>
                    </tr>  
                <?php  endforeach;?>
            </tbody>
        </table>                                                        
    </div>
</div>