<!DOCTYPE html>
<html>
<head>
<title>Productividapp :: Parvadapps</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Parvadapps, Productividapp" />
<link rel="shortcut icon" href="/assets/img/favicon.ico" type="image/x-icon">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

<link href="/landing/css/bootstrap.css" rel='stylesheet' type='text/css' />
<link href="/landing/css/style.css" rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Exo:100,200,300,400,500,600,700,800,900,100italic,200italic,300italic,400italic,500italic,600italic,700italic,800italic,900italic' rel='stylesheet' type='text/css'>
<script src="/landing/js/jquery-1.11.0.min.js"></script>
<!---- start-smoth-scrolling---->
<script type="text/javascript" src="/landing/js/move-top.js"></script>
<script type="text/javascript" src="/landing/js/easing.js"></script>
<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
			function locationLogin(){
				window.location.href = '/main/main/index';
				return false;
			}			
		</script>

<!---- start-smoth-scrolling---->
</head>
<body>
	<div class="header" id="home">
		<div class="container">
			<div class="logo">
				<a href="index.html"><img src="/landing/images/logo.png" alt=""></a>
			</div>
			<div class="navigation">
			 <span class="menu"></span> 
				<ul class="navig">
					<li><a href="index.html" class="scroll">INICIO</a><span> </span></li>
					<li><a href="#features" class="scroll">CARACTERISTICAS</a><span> </span></li>
					<!--<li><a href="#countdown" class="scroll">COUNTDOWN</a><span> </span></li>-->
					<li><a href="#pricing" class="scroll">PRECIOS</a><span> </span></li>
					<!--<li><a href="#testimonials" class="scroll">TESTIMONIOS</a><span> </span></li>-->
					<li><a href="#contact" class="scroll">CONTACTO</a><span> </span></li>
					<li><a href="javascript:void(0)" onClick="locationLogin();" class="scroll">INGRESAR</a><span> </span></li>
				</ul>
			</div>
				 <!-- script-for-menu -->
		 <script>
				$("span.menu").click(function(){
					$(" ul.navig").slideToggle("slow" , function(){
					});
				});
		 </script>
		 <!-- script-for-menu -->
		</div>
	</div>
	<!--start-banner-->
	<div class="banner">
		<div class="container">
			<div class="banner-top">
				<h1>Productividapp</h1>
				<p>“Conjunto de soluciones móbiles/web que te ayudarán a la planeación, control y organización de actividades realizadas al exterior de tu empresa a fin de optimizar los recursos empleados en ellas.”</p>
			</div>
			<div class="banner-bottom">
				<div class="col-md-4 banner-left">
					<a href="#">DESCARGAR</a>
				</div>
				<div class="col-md-4 banner-middle">
					<img src="/landing/images/iphone.png" alt="" />
				</div>
				<div class="col-md-4 banner-right">
					<a href="#">MAS INFORMACIÓN</a>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--start-banner-->
	<!--start-feature-->
	<div class="feature" id="features">
		<div class="container">
			<div class="feature-main">
				<h3>Productividapp</h3>
				<P>ayuda a mejorar y controlar los procesos de:</P>
			</div>
				<div class="feature-bottom">
					<div class="col-md-6 feature-bottom-left">
						<div class="ftr-one">
							<div class="feature-left">
								<img src="/landing/images/feature-1.png" alt="" />
							</div>
							<div class="feature-right">
								<h4>Información en tiempo real</h4>
								<p>Permite administrar la información a través de cualquier dispositivo electrónico, ya que estará disponible en un espacio de almacenamiento virtual (nube).</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="ftr-one">
							<div class="feature-left">
								<img src="/landing/images/feature-3.png" alt="" />
							</div>
							<div class="feature-right">
								<h4>Movilidad</h4>
								<p>La aplicación móvil de Productividapp convierte su dispositivo móvil en una oficina de ventas portátil. Puede registrar llamadas, responder a clientes potenciales u oportunidades laborales, o supervisar los tableros sin importar dónde se encuentre.</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="ftr-one">
							<div class="feature-left">
								<img src="/landing/images/feature-5.png" alt="" />
							</div>
							<div class="feature-right">
								<h4>Chat</h4>
								<p>Le permitirá implementar un servicio de comunicación profesional en línea con su personal vía chat, basta con seguir 3 pasos de instalación para conseguir que su Sitio Web tenga un aspecto profesional a nivel de comunicación. </p>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="col-md-6 feature-bottom-left">
						<div class="ftr-one">
							<div class="feature-left">
								<img src="/landing/images/feature-2.png" alt="" />
							</div>
							<div class="feature-right">
								<h4>Facil de Utilizar</h4>
								<p>Un sistema amigable, pero sobre todo sencillo y facil de comenzar a utilizar. </p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="ftr-one">
							<div class="feature-left">
								<img src="/landing/images/feature-4.png" alt="" />
							</div>
							<div class="feature-right">
								<h4>Localización</h4>
								<p>Esta aplicación ofrece servicios de localización GPS de personas, localización GPS de trabajadores, geolocalización y gestión de flotas, puntos de interés y generación de multitud de informes exportables a formatos como HTML, CSV, XML o Excel.</p>
							</div>
							<div class="clearfix"></div>
						</div>
						<div class="ftr-one">
							<div class="feature-left">
								<img src="/landing/images/feature-6.png" alt="" />
							</div>
							<div class="feature-right">
								<h4>Mejores Decisiones</h4>
								<p>Obtenga la información necesaria para tomar decisiones más inteligentes. Con Salesforce, la información está en un solo lugar, de modo que es más sencillo establecer prioridades y tomar decisiones rápidas basadas en la información más correcta y actualizada disponible.</p>
							</div>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
		</div>
	</div>
	<!--end-feature-->
	<!--start-news-->
	<!--
	<div class="top-news">
	<div class="news">
		<div class="container">
			<div class="news-main">
				<h3>Appmo Newsletter</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur</p>
			</div>
			<div class="news-top">
				<input type="text" value="E-mail adres.." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'E-mail adres..';}"/>
				<div class="contact-but">
						<input type="submit" value="SUBSCRIBE" />
				</div>
			</div>
			<div class="new-bottom">
				<img src="/landing/images/slide-back.png" alt="" />
			</div>
			<script src="/landing/js/responsiveslides.min.js"></script>
						 <script>
							// You can also use "$(window).load(function() {"
							$(function () {
							  // Slideshow 4
							  $("#slider4").responsiveSlides({
								auto: true,
								pager: false,
								nav: false,
								speed: 500,
								namespace: "callbacks",
								before: function () {
								  $('.events').append("<li>before event fired.</li>");
								},
								after: function () {
								  $('.events').append("<li>after event fired.</li>");
								}
							  });
						
							});
						  </script>						
						<div  id="top" class="callbacks_container">
							<ul class="rslides" id="slider4">
								<li>
									<div class="new-slid">
										<p>“  dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis ”</p>
										<h4>Mohamed Saed</h4>
										<img src="/landing/images/slide-1.png" alt="">
									</div>
								</li>
								<li>
									<div class="new-slid">
										<p>“  sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis ”</p>
										<h4>Cylon</h4>
										<img src="/landing/images/slide-2.png" alt="">
									</div>
								</li>
							</ul>
						</div>
				</div>
			</div>
		</div>-->
	<!--end-news-->
	<!--Slider-Starts-Here-->
				<script src="/landing/js/responsiveslides.min.js"></script>
			  <script>
			    // You can also use "$(window).load(function() {"
			    $(function () {
			      // Slideshow 4
			      $("#slider4").responsiveSlides({
			        auto: true,
			        pager: true,
			        nav: true,
			        speed: 500,
			        namespace: "callbacks",
			        before: function () {
			          $('.events').append("<li>before event fired.</li>");
			        },
			        after: function () {
			          $('.events').append("<li>after event fired.</li>");
			        }
			      });
			
			    });
			  </script>
			<!--End-slider-script-->
	<!--start-app1-->
	<!--
	<div class="app1" id="countdown">
		<div class="container">
			<div class="app1-top">
				<h3>Appmo Newsletter</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur</p>
			</div>	
				<div class="app1-bottom">
					<div class="col-md-6 app1-left">
						<div class="app1-main">
							<span>03.05.2014</span>
							<h4>dolor sit amet, consectetuer adipiscing elit</h4>
							<p>natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim</p>
						</div>
						<div class="app1-main">
							<span>09.05.2014</span>
							<h4>dolor sit amet, consectetuer adipiscing elit</h4>
							<p>natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim</p>
						</div>
						<div class="app1-main">
							<span>03.05.2014</span>
							<h4>dolor sit amet, consectetuer adipiscing elit</h4>
							<p>natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim</p>
						</div>
					</div>
					<div class="col-md-6 app1-left">
						<div class="app1-main">
							<span>15.05.2014</span>
							<h4>dolor sit amet, consectetuer adipiscing elit</h4>
							<p>natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim</p>
						</div>
						<div class="app1-main">
							<span>10.05.2014</span>
							<h4>dolor sit amet, consectetuer adipiscing elit</h4>
							<p>natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim</p>
						</div>
						<div class="app1-main">
							<span>09.05.2014</span>
							<h4>dolor sit amet, consectetuer adipiscing elit</h4>
							<p>natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim</p>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
		</div>
	</div>-->
	<!--end-app1-->
	<!--start-screen-->
	<div class="screen">
		<div class="container">
			<div class="screen-top">
				<h3>Screenshots Of App</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur</p>
			</div>
			<div class="screen-bottom">
				<div class="col-md-3 screen-left">
					<a href="single.html" class="b-link-stripe b-animate-go  thickbox">
									<img class="port-pic" class="img-responsive" src="/landing/images/screen-1.png" />
									<div class="b-wrapper">
										<h2 class="b-animate b-from-left b-from   b-delay03 ">
											<span>orem ipsum dolor sit amet, consectetuer adipiscing lit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis</span>
										</h2>
									</div>
								</a>
				</div>
				<div class="col-md-3 screen-left">
					<a href="single.html" class="b-link-stripe b-animate-go  thickbox">
									<img class="port-pic" class="img-responsive" src="/landing/images/screen-2.png" />
									<div class="b-wrapper">
										<h2 class="b-animate b-from-left b-from   b-delay03 ">
											<span>orem ipsum dolor sit amet, consectetuer adipiscing lit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis</span>
										</h2>
									</div>
								</a>
				</div>
				<div class="col-md-3 screen-left">
					<a href="single.html" class="b-link-stripe b-animate-go  thickbox">
									<img class="port-pic" class="img-responsive" src="/landing/images/screen-3.png" />
									<div class="b-wrapper">
										<h2 class="b-animate b-from-left b-from   b-delay03 ">
											<span>orem ipsum dolor sit amet, consectetuer adipiscing lit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis</span>
										</h2>
									</div>
								</a>
				</div>
				<div class="col-md-3 screen-left">
					<a href="single.html" class="b-link-stripe b-animate-go  thickbox">
									<img class="port-pic" class="img-responsive" src="/landing/images/screen-4.png" />
									<div class="b-wrapper">
										<h2 class="b-animate b-from-left b-from   b-delay03 ">
											<span>orem ipsum dolor sit amet, consectetuer adipiscing lit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis</span>
										</h2>
									</div>
								</a>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-screen-->
	<!--start-member-->
	<div class="member" id="pricing">
		<div class="container">
			<div class="member-top">
				<h3>Member Packed</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur</p>
			</div>
			<div class="member-bottom">
				<div class="col-md-3 member-bottom-left">
					<div class="member-one">
						<div class="mem-back">
							<p>29<span>$</span></p>
							<label>monthly</label>
						</div>
						<div class="mem-two">
							<h5>1 Websites</h5>
							<h5>1 User</h5>
							<h5>2 gb Storage</h5>
							<h5>1000 GB Bandwith</h5>
							<h5>Support Ticjet System</h5>
						</div>
					</div>
				</div>
				<div class="col-md-3 member-bottom-left">
					<div class="member-one">
						<div class="mem-back">
							<p>50<span>$</span></p>
							<label>monthly</label>
						</div>
						<div class="mem-two">
							<h5>1 Websites</h5>
							<h5>1 User</h5>
							<h5>2 gb Storage</h5>
							<h5>1000 GB Bandwith</h5>
							<h5>Support Ticjet System</h5>
						</div>
					</div>
				</div>
				<div class="col-md-3 member-bottom-left">
					<div class="member-one">
						<div class="mem-back">
							<p>80<span>$</span></p>
							<label>monthly</label>
						</div>
						<div class="mem-two">
							<h5>1 Websites</h5>
							<h5>1 User</h5>
							<h5>2 gb Storage</h5>
							<h5>1000 GB Bandwith</h5>
							<h5>Support Ticjet System</h5>
						</div>
					</div>
				</div>
				<div class="col-md-3 member-bottom-left">
					<div class="member-one">
						<div class="mem-back">
							<p>152<span>$</span></p>
							<label>monthly</label>
						</div>
						<div class="mem-two">
							<h5>1 Websites</h5>
							<h5>1 User</h5>
							<h5>2 gb Storage</h5>
							<h5>1000 GB Bandwith</h5>
							<h5>Support Ticjet System</h5>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-member-->
	<!--end-team-->
	<!--
	<div class="team" id="testimonials">
		<div class="container">
			<div class="team-top">
				<h3>Apmo Team</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur</p>
			</div>
			<div class="team-bottom">
				<div class="col-md-4 team-left">
					<img src="/landing/images/team-back.png" alt=""/>
					<div class="team-one">
						<img src="/landing/images/team-1.png" alt=""/>
						<h4>Mohamed Saed</h4>
						<h5>UI / UX</h5>
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing Aenean commodo</p>
					</div>
				</div>
				<div class="col-md-4 team-left">
					<img src="/landing/images/team-back.png" alt=""/>
					<div class="team-one">
						<img src="/landing/images/team-2.png" alt=""/>
						<h4>Aya Mostafa</h4>
						<h5>Seo</h5>
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing Aenean commodo</p>
					</div>
				</div>
				<div class="col-md-4 team-left">
					<img src="/landing/images/team-back.png" alt=""/>
					<div class="team-one">
						<img src="/landing/images/team-3.png" alt=""/>
						<h4>Osama Elwan</h4>
						<h5>Web Dsigne</h5>
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing Aenean commodo</p>
					</div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>-->
	<!--end-team-->
	<!--start-support-->
	<div class="support">
		<div class="container">
			<div class="support-main">
				<div class="col-md-3 support-left">
					<img src="/landing/images/support-1.png" alt=""/>
				</div>
				<div class="col-md-3 support-left">
					<img src="/landing/images/support-2.png" alt=""/>
				</div>
				<div class="col-md-3 support-left">
					<img src="/landing/images/support-3.png" alt=""/>
				</div>
				<div class="col-md-3 support-left">
					<img src="/landing/images/support-4.png" alt=""/>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--end-support-->
	<!--start-map-->
	<!--
	<div class="map">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13807.03365156693!2d31.219684!3d30.10110455!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14584035757b8e1b%3A0x7d32793a8a39412a!2sWarraq+Al+Hadar%2C+Warraq+Al+Arab%2C+Al+Warraq%2C+Giza+Governorate%2C+Egypt!5e0!3m2!1sen!2sin!4v1424255939192" frameborder="0" style="border:0"></iframe>
	</div>-->
	<!--end-map-->
	<!--start-contact-->
	<div class="contact" id="contact">
		<div class="container">
			<div class="contact-top">
				<h3>LEAVE US A THOUGHT</h3>
				<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur</p>
			</div>
			<div class="contact-bottom">
				<div class="col-md-8 contact-left">
					<input type="text" value="Your Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Your Name';}"/>
					<input type="text" value="Your Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Your Email';}"/>
				</div>
				<div class="col-md-4 contact-right">
					<h6>Your Company App Name<span>Cairo Egypt , St 145 in al nozha</span></h6>
					<p>00201026470241</p>
					<p><a href="mailto:example@email.com">Masedup@gmail.com</a></p>
					<p>Themeforest.net</p>
				</div>
				<div class="contact-textarea">
					<textarea value="Your Message" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Your Message</textarea>
				</div>
				<div class="contact-submit">
					<input type="submit" value="Submit" />
				</div>
			</div>
			<div class="social">
				<ul>
					<li><a href="#"><span class="fb"> </span></a></li>
					<!--<li><a href="#"><span class="p"> </span></a></li>-->
					<li><a href="#"><span class="twt"> </span></a></li>
					<li><a href="#"><span class="g"> </span></a></li>
					<!--<li><a href="#"><span class="rss"> </span></a></li>-->
				</ul>
			</div>
		</div>
	</div>
	<!--end-contact-->
	<!--start-footer-->
	<div class="footer">
		<div class="container">
			<div class="footer-text">
				<p>Parvadapps <a href="http://www.parvadapps.com/"> - Productividad</a></p>
			</div>
		</div>
		 <script type="text/javascript">
									$(document).ready(function() {
										/*
										var defaults = {
								  			containerID: 'toTop', // fading element id
											containerHoverID: 'toTopHover', // fading element hover id
											scrollSpeed: 1200,
											easingType: 'linear' 
								 		};
										*/
										
										$().UItoTop({ easingType: 'easeOutQuart' });
										
									});
								</script>
		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
	</div>
	<!--End-footer-->			
</body>
</html>