<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Productividapp</title>
    <link rel="shortcut icon" href="favicon.ico"/>    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all"/>    
    <link rel="stylesheet" type="text/css" href="/assets/plugins/font-awesome/css/font-awesome.min.css"/>    
    <link rel="stylesheet" type="text/css" href="/assets/plugins/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/plugins/uniform/css/uniform.default.css"/>    
    <link rel="stylesheet" type="text/css" href="/assets/css/style-metronic.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/css/style.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/css/style-responsive.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/plugins/bootstrap-toastr/toastr.min.css"/>

    <link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2-metronic.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/plugins/jquery-multi-select/css/multi-select.css"/>
    <link rel="stylesheet" type="text/css" href="/assets/plugins/data-tables/DT_bootstrap.css"/>    
    <link rel="stylesheet" type="text/css" href="/css/app.css">       
    <link rel="stylesheet" type="text/css" href="/assets/css/themes/light.css"/>      
</head>
<!--  --> 
<body class="page-header-fixed page-sidebar-closed">
    <?php echo $this->render('header.phtml', 
                                    array (
                                      'dataUser'    => $this->dataUser,
                                    )); ?>
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->    
        <?php echo $this->render('menu.phtml', 
                                    array(
                                      'dataUser'    => $this->dataUser,
                                    )); ?>
       <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">            
            <div class="page-content-body">
                <?php echo $this->layout()->content; ?>
            </div>                
        </div>
    <!-- END CONTENT -->
    </div>
    <?php echo $this->partial('footer.phtml') ?>      


    <script type="text/javascript" src="/assets/plugins/jquery-1.10.2.min.js" ></script>
    <script type="text/javascript" src="/assets/plugins/jquery-migrate-1.2.1.min.js"></script>
    
    <script type="text/javascript" src="/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>    

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script type="text/javascript" src="/assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script type="text/javascript" src="/assets/scripts/custom/ui-toastr.js"></script>
    <script type="text/javascript" src="/assets/scripts/custom/index.js"></script>
    <script type="text/javascript" src="/assets/scripts/custom/table-managed.js"></script>  

    <script src="/assets/plugins/bootstrap-modal/js/bootstrap-modal.js" type="text/javascript"></script>    
    <script src="/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js" type="text/javascript"></script>
    
    <script type="text/javascript" src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script type="text/javascript" src="/assets/scripts/core/app.js"></script>

      <?php echo $this->headLink() ?>
      <?php echo $this->headStyle() ?>
      <?php echo $this->headScript() ?>
    <script>
    jQuery(document).ready(function() {    
       App.init();
    });
    </script>      
</body>
</html>