<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Productividapp</title>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>    
    <link href="/assets/css/print.css" rel="stylesheet" type="text/css" media="print"/>
    <link href="/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>    
</head>
<body>
    <script type="text/javascript" src="/assets/plugins/jquery-1.10.2.min.js" ></script>
    <script type="text/javascript" src="/assets/plugins/jquery-migrate-1.2.1.min.js"></script>
    
    <script type="text/javascript" src="/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/data-tables/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/assets/plugins/data-tables/DT_bootstrap.js"></script>    

    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script type="text/javascript" src="/assets/plugins/bootstrap-toastr/toastr.min.js"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script type="text/javascript" src="/assets/scripts/custom/ui-toastr.js"></script>
    <script type="text/javascript" src="/assets/scripts/custom/index.js"></script>
    <script type="text/javascript" src="/assets/scripts/custom/table-managed.js"></script>  
    <!--<script type="text/javascript" src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js"></script>  -->
    <script type="text/javascript" src="/assets/scripts/core/app.js"></script>    
    <?php echo $this->layout()->content; ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>              
</body>
</html>