    <ul class="nav sidebar-menu ">
        <?php $controlMenu = -1; ?>
        <?php foreach($this->modules as $key => $items): ?>
            <?php if($items['SUBMENU']==0): ?>
                <?php foreach($this->modules as $key => $itemsModule): ?>
                    <?php if($itemsModule['ID_MENU'] == $items['ID_MENU']):?>
                        <li class="<?php echo ($this->moduleInfo['ID_MENU']==$items['ID_MENU']) ? 'active open': ''; ?>">
                            <a href="<?php echo $itemsModule['S_MODULE'];?>&ssKeyConfigTokenAction=<?php echo $this->nRandom.''.rand(5, 255);?>">
                                <i class="menu-icon <?php echo $items['ICONO'];?>"></i>
                                <span class="menu-text"> <?php echo $items['N_DESCRIPCION'];?> </span>
                            </a>
                        </li>
                    <?php endif;?>
                <?php endforeach;?>
            <?php else:?>
                <?php if($controlMenu!=$items['IDMENU']): ?>
                    <?php $controlMenu=$items['IDMENU']; ?>
                        <li class="<?php echo ($this->moduleInfo['ID_MENU']==$items['ID_MENU']) ? 'active open': ''; ?>">
                            <a href="#" class="menu-dropdown">
                                <i class="menu-icon <?php echo $items['ICONO'];?>"></i>
                                <span class="menu-text"> <?php echo $items['N_DESCRIPCION'];?> </span>
                                <i class="menu-expand"></i>
                            </a>
                            <ul class="submenu">
                                <?php foreach($this->modules as $key => $itemsModule): ?>
                                    <?php if($itemsModule['ID_MENU'] == $items['ID_MENU']):?>
                                        <li class="<?php echo ($this->moduleInfo['ID_MODULO']==$itemsModule['ID_MODULO']) ? 'active': ''; ?>">
                                            <a href="<?php echo $itemsModule['S_MODULE'];?>&ssKeyConfigTokenAction=<?php echo $this->nRandom.''.rand(5, 255);?>">
                                                <span class="menu-text"><?php echo $itemsModule['M_DESCRIPCION']; ?></span>
                                            </a>
                                        </li>    
                                    <?php endif;?>
                                <?php endforeach;?>
                            </ul>
                        </li>                                       
                <?php endif;?>
            <?php endif;?>
        <?php endforeach;?>
    </ul>
</div>