<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/assets/js/fuelux/wizard/wizard-custom.js') ?> 
<?php $this->headScript()->appendFile('/assets/js/select2/select2.js') ?> 
<?php $this->headScript()->appendFile('/js/modules/dates/jsValidateLocation.js') ?> 
<?php $this->headScript()->captureStart() ?>
    <?php $sAddress = ''; ?>
    <?php foreach($this->aAddress as $key => $items):?> 
        <?php $sAddress.= ($sAddress!="") ? ',' : ''; ?>
        <?php $dataItem = $items['ESTADO'].",".
                          $items['MUNICIPIO'].",".
                          $items['COLONIA'].",".
                          $items['CALLE'].",".
                          $items['CP'].",".
                          $items['NUMERO_INT'].",".
                          $items['NUMERO_EXT'].",".
                          $items['REFERENCIAS'].",".
                          $items['LATITUD'].",".
                          $items['LONGITUD'];?>
        <?php $sAddress.= $items['ID_DOMICILIO'].":'".$dataItem."'";?>
    <?php endforeach;?> 
    var aDataAddress = {<?php echo $sAddress;?>}
<?php $this->headScript()->captureEnd(); ?>

<input type="hidden" id="inputModule" value="<?php echo $this->moduleInfo['SCRIPT']; ?>"/>
    <div class="page-header position-relative">
        <div class="header-title">
            <h1>
                Citas
            </h1>
            <small>Nueva Cita</small>
        </div>        
        <!--
        <div class="pull-right">
            <a class="btn default" name="back" type="button" href="/dbman/main/index?ssIdource=mforms&action=tablegral"><i class="fa fa-angle-left"></i> Regresar</a>           
        </div>  -->      
    </div>
     <!--/Page Header -->     
    <div id="divBodyPage" class="page-body">
        <?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
            <div class="alert alert-block alert-danger fade in block-inner">
                <h6><i class="icon-cancel-circle"></i> Error</h6>
                <hr>
                <p>Usted no tiene permiso para ver esta información.</p>
            </div>
        <?php else:?>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">

                    <div id="WiredWizard" class="wizard wizard-wired" data-target="#WiredWizardsteps">
                        <ul class="steps">
                            <li data-target="#wiredstep1"><span class="step">1</span><span class="title">Información General</span><span class="chevron"></span></li>
                            <li data-target="#wiredstep2" class="active"><span class="step">2</span><span class="title">Ubicación</span> <span class="chevron"></span></li>
                            <li data-target="#wiredstep2"><span class="step">3</span><span class="title">Información Adicional</span> <span class="chevron"></span></li>
                            <li data-target="#wiredstep2"><span class="step">4</span><span class="title">Confirmar</span> <span class="chevron"></span></li>                            
                        </ul>

                    </div>
                    <div class="step-content" id="WiredWizardsteps">
                        <form id="formDbman" class="form-horizontal" role="form" method="POST" action="/dates/main/location">
                            <input type="hidden" id="optReg" name="optReg" value="<?php echo (@$this->aData['inputFolio']!="") ? 'update': 'new';?>" />
                            <input type="hidden" id="strTabSelected" name="strTabSelected" value="<?php echo $this->tabSelected;?>" />                        
                            <div class="step-pane active" id="wiredstep1">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-6">
                                        <div class="form-group">
                                            <label for="inputFolio" class="col-sm-2 control-label no-padding-right">Dirección</label>
                                            <div class="col-sm-10">
                                                <select id="inputAddress" name="inputAddress" style="width:100%;" class="formInput">
                                                    <option value="-1">Seleccione una dirección</option>
                                                    <?php echo $this->cboAddress;?>
                                                    <option value="na">Nueva Dirección</option>
                                                </select>                                                
                                            </div>
                                        </div>
                                        <div id="divAddress" class="optionsShow">
                                            <div class="form-group">
                                                <label for="inputCalle" class="col-sm-2 control-label no-padding-right">Calle</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control formInput" name="inputCalle" id="inputCalle" placeholder="Calle" value="<?php echo @$this->aDataLocation['inputCalle'];?>" readonly>
                                                </div>
                                            </div>                                           
                                            <div class="form-group">
                                                <label for="inputNext" class="col-sm-2 control-label no-padding-right">No. Ext.</label>
                                                <div class="col-sm-10">
                                                     <div class="col-lg-4 col-sm-4 col-xs-4 no-padding">
                                                        <input type="text" class="form-control formInput" name="inputNext" id="inputNext" placeholder="No. Ext." value="<?php echo @$this->aDataLocation['inputNext'];?>" readonly>                                          
                                                     </div>
                                                     <div class="col-lg-6 col-sm-6 col-xs-6 no-padding">
                                                        <div class="form-group no-padding no-margin">
                                                            <label for="inputNint" class="col-sm-4 control-label no-padding-right">No. Int.</label>
                                                            <div class="col-sm-8">
                                                                <input type="text" class="form-control formInput" name="inputNint" id="inputNint" placeholder="No. Int." value="<?php echo @$this->aDataLocation['inputNint'];?>" readonly>                                       
                                                            </div>
                                                        </div> 
                                                     </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputColonia" class="col-sm-2 control-label no-padding-right">Colonia</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control formInput" name="inputColonia" id="inputColonia" placeholder="Colonia" value="<?php echo @$this->aDataLocation['inputColonia'];?>" readonly>                                          
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputMun" class="col-sm-2 control-label no-padding-right">Municipio</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control formInput" name="inputMun" id="inputMun" placeholder="Municipio" value="<?php echo @$this->aDataLocation['inputMun'];?>" readonly>                                          
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputEdo" class="col-sm-2 control-label no-padding-right">Estado</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control formInput" name="inputEdo" id="inputEdo" placeholder="Estado" value="<?php echo @$this->aDataLocation['inputEdo'];?>" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputCp" class="col-sm-2 control-label no-padding-right">CP</label>
                                                <div class="col-sm-10">
                                                    <div class="col-lg-4 col-sm-4 col-xs-4 no-padding">
                                                        <input type="text" class="form-control formInput" name="inputCp" id="inputCp" placeholder="No. Ext." value="<?php echo @$this->aDataLocation['inputCp'];?>" readonly>
                                                    </div>
                                                    <div id="btnOnMap" class="col-lg-8 col-sm-8 col-xs-8 no-padding centerButton" style="display:none;">
                                                        <a href="javascript:searchAddress()" class="btn btn-palegreen pull-right"><i class="fa fa-map-marker"></i>Buscar Posición</a>
                                                    </div>
                                                </div>
                                            </div>                                            
                                            <div class="form-group">
                                                <label for="inputRefs" class="col-sm-2 control-label no-padding-right">Referencias</label>
                                                <div class="col-sm-10">
                                                    <input type="text" class="form-control formInput" name="inputRefs" id="inputRefs" placeholder="Referencias" value="<?php echo @$this->aDataLocation['inputRefs'];?>" readonly>                                       
                                                </div>
                                            </div>                                               
                                        </div>     
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-6 optionsShow">
                                        <div class="form-group center-text" style="height: 30px;">
                                            <span>Ubicación</span>
                                        </div> 
                                        <div class="form-group">
                                            <label for="inputLatitud" class="col-sm-2 control-label no-padding-right">Latitud</label>
                                            <div class="col-sm-6">
                                                <input type="text" class="form-control formInput" name="inputLatitud" id="inputLatitud" placeholder="Latitud" value="<?php echo @$this->aDataLocation['inputLatitud'];?>" readonly>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputLongitud" class="col-sm-2 control-label no-padding-right">Longitud</label>
                                            <div class="col-sm-6">
                                                <input type="text" class="form-control formInput" name="inputLongitud" id="inputLongitud" placeholder="Longitud" value="<?php echo @$this->aDataLocation['inputLongitud'];?>" readonly>
                                            </div>
                                            <div class="col-sm-4 centerButton" style="display:none;">
                                                <a href="javascript:centerOnMap(1);" class="btn btn-palegreen pull-right"><i class="fa fa-map-marker"></i>Buscar Coordenadas</a>
                                            </div>
                                        </div>
                                        <div id="map"  style="width:100%;height:250px;"></div>    
                                    </div>
                                </div>
                                <div class="row margin-t5px">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <div class="pull-right">
                                            <a href="/dates/main/index" class="btn btn-info"><i class="fa fa-angle-left"></i>Regresar</a>
                                            <button type="submit" class="btn btn-info">Siguiente <i class="fa fa-angle-right"></i></button>
                                            <button type="button" class="btn default" onClick="location.href='/dates/main/index';">Cancelar</button>
                                        </div>
                                    </div>
                                </div>                        
                            </div> 
                        </form>                            
                    </div>
                </div>
            </div>
        <?php endif;?>
    </div>