<?php $this->headScript()->appendFile('/js/modules/users/validateUsers.js') ?>  
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>				
<input type="hidden" id="inputModule" value="<?php echo $this->moduleInfo['SCRIPT']; ?>"/>
<div class="row">
	<div class="col-md-12">
		<ul class="page-breadcrumb breadcrumb">
			<li>
				<i class="fa fa-home"></i>
				<a href="/main/main/inicio">
					Inicio
				</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="<?php echo $this->moduleInfo['SCRIPT'];?>">
					<?php echo $this->moduleInfo['DESCRIPCION'];?>
				</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="#">
					Detalle del Usuario
				</a>
			</li>							
		</ul>
	</div>
</div>

<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Información del usuario
		</div>
		<div class="tools">
			<!--<a href="javascript:;" class="reload">
			</a>			
			<a href="javascript:;" class="collapse">
			</a>
			<a href="#portlet-config" data-toggle="modal" class="config">
			</a>

			<a href="javascript:;" class="remove">
			</a>-->
		</div>
	</div>
	<div class="portlet-body form">
		<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
			<div id="divpErrorLogin" class="alert alert-danger alert-dismissable" style="display:block;">
			  <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
			  <h4>Error</h4>
			  <div>Usted no tiene permiso para ver esta información</div>
			</div>						
		<?php else:?>

		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#tabGral">Información</a></li>
	        <?php if($this->idToUpdate>0 && @$this->data['FLAG_OPERACIONES']==1):?>
				<li><a data-toggle="tab" href="#tabSecond">Horarios</a></li>
	    	<?php endif;?>
		</ul>
		<div class="tab-content">					
			<div id="tabGral" class="tab-pane <?php echo (@$this->eventAction) ? '':'active';?> ">
				<?php if($disabled!='disabled'):?>
					<form name="FormData" id="FormData" method="POST" action="<?php echo str_replace('index', 'getinfo', $this->moduleInfo['SCRIPT']); ;?>" class="form-horizontal">
				<?php endif;?>
					<input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
			    	<input type="hidden" name="catId"  value="<?php echo $this->catId; ?>" id="catId" />
			    	
					<div class="alert alert-danger display-hide">
						<button class="close" data-close="alert"></button>
						El registro contiene uno o mas errores, favor de verificarlos.
					</div>
					<div class="alert alert-success display-hide">
						<button class="close" data-close="alert"></button>
						Información correcta
					</div>		    	
			        <?php if($this->resultOp=='okRegister'): ?>
			            <div class="alert alert-success alert-dismissable">
			                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
			                Datos se almacenaron correctamente.
			            </div>  	
			        <?php endif; ?>		
			            	              
	            	<?php if(@$this->errors['eMail']):?>
			            <div class="alert alert-success alert-dismissable">
			                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
						  <h4>Error</h4>
						  <div>El E-mail no se encuentra disponible</div>
						</div>	
	            	<?php elseif(@$this->errors['eUsuario']):?>
			            <div class="alert alert-success alert-dismissable">
			                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
						  <h4>Error</h4>
						  <div>La Usuario no se encuentra disponible</div>
						</div>	                	
	            	<?php endif;?>			            	              
			        

			    	<div class="form-body">
						<div class="form-group">
							<label class="col-md-3 control-label">Sucursal<span class="required">*</span></label>
							<div class="col-md-4">
								<select class="form-control input-sm" name="inputSucursal" id="inputSucursal" <?php echo $disabled;?> >
									<option value="">Seleccionar una opción</option>
	                                <?php echo $this->aSucursales;?>
								</select>
							</div>
						</div>	

						<div class="form-group">
							<label class="col-md-3 control-label">Perfil<span class="required">*</span></label>
							<div class="col-md-4">
								<select class="form-control input-sm" name="inputPerfil" id="inputPerfil" <?php echo $disabled;?> autocomplete="off" >	
									<option value="">Seleccionar una opción</option>
	                                <?php echo $this->aPerfiles;?>
								</select>
							</div>
						</div>	
						<div class="form-group">
							<label class="col-md-3 control-label">Usuario<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="text" name="inputUsuario" id="inputUsuario" data-required="1" class="form-control" value="<?php echo @$this->data['USUARIO']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label">Contraseña<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="password" name="inputPassword" id="inputPassword" data-required="1" class="form-control" value="<?php echo @$this->data['']; ?>"  <?php echo $disabled;?> onChange="addValidatePass(this.value)" autocomplete="off" >	
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label">Confirmar Contraseña<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="password" name="inputPasswordC" id="inputPasswordC" class="form-control" value="<?php echo @$this->data['']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label">Nombre<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="text" name="inputNombre" id="inputNombre" data-required="1"  class="form-control" value="<?php echo @$this->data['NOMBRE']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label">Apellidos<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="text" name="inputApps" id="inputApps"  data-required="1" class="form-control" value="<?php echo @$this->data['APELLIDOS']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>		

						<div class="form-group">
							<label class="col-md-3 control-label">E-mail<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="mail" name="inputEmail" id="inputEmail"  data-required="1" class="form-control" value="<?php echo @$this->data['EMAIL']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label">Tel. Fijo</label>
							<div class="col-md-4">
								<input type="text" name="inputTelFijo" id="inputTelFijo" class="form-control" value="<?php echo @$this->data['TEL_FIJO']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>	

						<div class="form-group">
							<label class="col-md-3 control-label">Tel. móvil<span class="required">*</span></label>
							<div class="col-md-4">
								<input type="text" name="inputMovil" id="inputMovil" class="form-control" value="<?php echo @$this->data['TEL_MOVIL']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
							</div>
						</div>								

						<div class="form-group">
							<label class="col-md-3 control-label">Activo<span class="required">*</span></label>
							<div class="col-md-4">
								<select class="form-control input-sm" name="inputEstatus" id="inputEstatus" <?php echo $disabled;?> >
									<option value="">Seleccionar una opción</option>
	                                <?php echo $this->aStatus;?>
								</select>
							</div>
						</div>

						<div class="form-group">
							<label class="col-md-3 control-label">Operaciones<span class="required">*</span></label>
							<div class="col-md-4">
								<select class="form-control input-sm" name="inputOperaciones" id="inputOperaciones" <?php echo $disabled;?> >
									<option value="">Seleccionar una opción</option>
	                                <?php echo $this->aOperaciones;?>
								</select>
							</div>
						</div>	

						<div class="form-group">
							<label class="col-md-3 control-label">Último Acceso</label>
							<div class="col-md-4">
								<label><?php echo @$this->data['ULTIMO_ACCESO']; ?></label>
							</div>
						</div>	
					</div>			
					<?php if($disabled!='disabled'):?>
					<div class="form-actions fluid">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn blue btnSave">Guardar</button>
							<button type="button" class="btn default" onClick="location.href='<?php echo $this->moduleInfo['SCRIPT']; ?>';">Cancelar</button>
						</div>
					</div>			
					<?php endif;?>	
				<?php if($disabled!='disabled'):?>
				</form>
				<?php endif;?>
			</div>
			<div id="tabSecond" class="tab-pane <?php echo (@$this->eventAction) ? 'active':'';?>">				
				<?php if(@$this->eventAction): ?>
					<div class="alert alert-success">
						<button class="close" data-close="alert"></button>
						Datos se almacenaron correctamente.
					</div>		                    	              
                <?php endif; ?>
				<?php if($disabled!='disabled'):?>								
				<form method="POST" action="<?php echo str_replace('index', 'getinfo', $this->moduleInfo['SCRIPT']); ;?>" >
					<input type="hidden" name="optReg" value="addEvento" />
					<input type="hidden" id="catId" name="catId" value="<?php echo $this->catId; ?>" />
				<?php endif;?>	
			    	<div class="form-body row-min-h300 ">
	                    <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
	                        <thead>
	                            <tr>                                        
	                                <th style="width:100px;">
										<input type="checkbox" onClick="optionAll(this.checked);"> &nbsp;Todos 
	                                </th>
	                                <th>Hora Inico - Hora Fin</th>
	                            </tr>
	                        </thead>
	                        <tbody>						                     	
	                        	<?php foreach(@$this->aHorarios as $key => $items):?>
	                        		<tr>
	                        			<td><input name="inputsCheck<?php echo $items['ID_HORARIO'];?>" class="chkOn" type="checkbox" <?php echo ($items['ASSIGN']) ? 'checked':'';?>></td>
	                        			<td><?php echo $items['HORARIOS'];?></td>
	                        		</tr>
	                        	<?php endforeach;?>
	                        </tbody>
	                    </table>   
					</div>					
					<?php if($disabled!='disabled'):?>
					<div class="form-actions fluid">
						<div class="col-md-offset-3 col-md-9">
							<button type="submit" class="btn blue btnSave" >Guardar</button>
							<button type="button" class="btn default" onClick="location.href='<?php echo $this->moduleInfo['SCRIPT']; ?>';">Cancelar</button>
						</div>
					</div>			
					<?php endif;?>						
				<?php if($disabled!='disabled'):?>
				</form>
				<?php endif;?>

			</div>						
		</div>	
		<!-- END FORM-->
		<?php endif;?>		
	</div>
</div>
	<div class="modal fade" id="ajax" role="basic" aria-hidden="true">
		<div class="page-loading page-loading-boxed">
			<img src="/assets/img/loading-spinner-grey.gif" alt="" class="loading">
			<span>
				&nbsp;&nbsp;Loading...
			</span>
		</div>
		<div class="modal-dialog">
			<div class="modal-content">
			</div>
		</div>
	</div>	