
<div class="portlet-title line">
	<div class="caption">
		<i class="fa fa-comments"></i> Mensajes de <?php echo @$this->aContacto['NOMBRE']." ".@$this->aContacto['APELLIDOS']; ?>
	</div>
	<div class="tools">
		
	</div>
</div>
<div class="portlet-body"  style="min-height: 450px;">

	<div class="scroller" style="height: 400px;" data-always-visible="1" data-rail-visible1="1">
		<ul class="chats">
			<?php foreach($this->aConversacion as $key => $items):?>
				<?php if($items['RECIBIO']==$this->dataUser['ID_USUARIO']):?>
					<li class="in">
						<img class="avatar img-responsive" alt="" src="/images/icons/<?php echo ($items['TEL_RECIBE']!="NULL" && $items['TEL_RECIBE']!=NULL) ? 'icon-phone.png': 'icon-user.png';?>"/>
						<div class="message">
							<span class="arrow">
							</span>
							<div class="name">
								<?php echo $items['N_ENVIA'];?> <?php echo ($items['TEL_RECIBE']!="NULL" && $items['TEL_RECIBE']!=NULL) ? ' - Tel. '.$items['TEL_RECIBE'] : '';?>	

								<span class="aTimeAgoMsg">
									<i class="fa fa-clock-o"></i> 
									 	<?php echo $items['CREADO'];?>
								</span>									 
							</div>
							<span class="body">
								<?php echo $items['MENSAJE'];?>								
							</span>
						</div>					
					</li>
				<?php else:?>
					<li class="out">
						<img class="avatar img-responsive" alt="" src="/images/icons/icon-user.png"/>
						<div class="message">
							<span class="arrow">
							</span>
							<div class="name">
								<span class="aTimeAgoMsg">
									<i class="fa fa-clock-o"></i> 
									 	<?php echo $items['CREADO'];?>
								</span>
							</div>							
							<span class="body">
								<?php echo $items['MENSAJE'];?>
							</span>
						</div>
					</li>
				<?php endif;?>				
			<?php endforeach;?>
		</ul>
	</div>
	<div class="chat-form">
		<input type="hidden" id="txtInput" value="<?php echo $this->data['catId'];?>"/>
		<div class="input-cont">
			<input class="form-control" id="inputMessage" type="text" placeholder="Enviar Mensaje a este contacto"/>
		</div>
		<div class="btn-cont">
			<span class="arrow">
			</span>
			<a href="javascript:sendMessage();" class="btn blue icn-only">
				<i class="fa fa-check icon-white"></i>
			</a>
		</div>
	</div>
</div>	