
<ul class="chats" id="listChats">
	<?php foreach($this->aConversacion as $key => $items):?>
		<?php if($items['RECIBIO']==$this->dataUser['ID_USUARIO']):?>
			<li class="in">
				<img class="avatar img-responsive" alt="" src="/images/icons/icon-user.png"/>
				<div class="message">
					<span class="arrow">
					</span>
					<span class="body">
						<?php echo $items['MENSAJE'];?>								
					</span>					
					<div class="name">
						<?php echo $items['N_ENVIA'];?> <?php //echo ($items['TEL_RECIBE']!="NULL" && $items['TEL_RECIBE']!=NULL) ? ' - Tel. '.$items['TEL_RECIBE'] : '';?>
						<span class="aTimeAgoMsg">
							<span class="badge badge-success badge-roundless pand0">
								<i class="fa fa-check "></i> 								
							</span>							
							<?php echo $items['CREADO'];?>															 	
						</span>									 
					</div>
				</div>					
			</li>
		<?php else:?>
			<li class="out">
				<img class="avatar img-responsive" alt="" src="/images/icons/icon-user.png"/>
				<div class="message">
					<span class="arrow">
					</span>
					<span class="body">
						<?php echo $items['MENSAJE'];?>
					</span>					
					<div class="name">
						<span class="aTimeAgoMsg">
							<?php $color= '';?>

							<?php if(isset($items['LEIDO']) && $items['PROCESADO']!="LEIDO"): ?>
								<span class="badge badge-success badge-roundless pand0">
									<i class="fa fa-check "></i> 								
								</span>	
							<?php elseif(isset($items['PROCESADO']) && $items['PROCESADO']!="NULL"): ?>
								<span class="badge badge-default badge-roundless pand0">
									<i class="fa fa-check"></i> 								
								</span>	
							<?php else:?>
								<i class="fa fa-clock-o"></i>
							<?php endif; ?>
							<?php echo $items['CREADO'];?>
						</span>
					</div>							

				</div>
			</li>
		<?php endif;?>				
	<?php endforeach;?>
</ul>	