<?php $this->headScript()->appendFile('/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js') ?>  
<?php $this->headScript()->appendFile('/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js') ?>  
<?php $this->headScript()->appendFile('/assets/plugins/jquery.blockui.min.js') ?> 
<?php $this->headScript()->appendFile('/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js') ?> 
<?php $this->headScript()->appendFile('/js/modules/messages/index.js') ?>  
<?php $this->headLink()->appendStylesheet('/assets/css/pages/blog.css') ?>
<?php $counter=0; $idFirst=-1;?>
<div class="row">
	<div class="col-md-12">
		<h3 class="page-title">
		Mensajes <small>Envio de mensajes a teléfonos.</small>
		</h3>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="col-md-3">
			<div class="portlet no-margin-b">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-user"></i>Contactos
					</div>
				</div>
				<div class="portlet-body form">
					<div class="list-group contact scroller" style="height: 450px;">
						<?php  foreach($this->listContact as $key => $items):?>
							<?php if($counter==0):?>
								<?php $idFirst = $items['ID'];?>
							<?php endif;?>
							<?php $counter++;?>
							<a class="list-group-item minHeight50" href="javascript:getConversation(<?php echo $items['ID'];?>);">								
								<img src="/images/icons/<?php echo ($items['TEL']!="NULL" && $items['TEL']!=NULL) ? 'icon-phone.png': 'icon-user.png';?>" class="avatar" alt="">
								<span  class="tittleContact">
									<?php echo $items['NOMBRE'];?> <?php echo ($items['TEL']!="NULL" && $items['TEL']!=NULL) ? ' - Tel. '.$items['TEL'] : '';?>
								</span>																
								<span class="aTimeAgo">
									 <i class="fa fa-clock-o"></i> 
									 	<?php if($items['HAGODAYS']>0):?>
									 		Mas de <?php echo $items['HAGODAYS'];?> dia (s).
									 	<?php elseif($items['HAGOHOURS']>0): ?>
									 		Hace <?php echo $items['HAGOHOURS'];?> hora (s).
									 	<?php elseif($items['HAGOMINS']>0): ?>
									 		Hace <?php echo $items['HAGOMINS'];?> minuto (s).
										<?php endif;?>
								</span>									
							</a>
						<?php endforeach;?>
						<input type="hidden" id="txtContactFirst" value="<?php echo $idFirst;?>"/>
					</div>					
				</div>
			</div>	
		</div>	
		<div class="col-md-9">
			<div class="portlet solid light-grey bordered no-margin-b">
				<div id="chats" >

				</div>
			</div>
			<!-- END PORTLET-->				
		</div>	
	</div>
</div>	