$().ready(function(){
    $('#formDbman').bootstrapValidator({
        live: 'true',
        excluded: [':disabled'],
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            <?php foreach($this->aFields as $key => $items):?>
                <?php if($items['VISIBLE']!=0 && $items['ID_VALIDACION']>0):?>
                    <?php echo 'input.'.$items['INPUT_NAME'];?> 
                    <?php echo $items['OPCIONES'];?>
                <?php endif;?>
            <?php endforeach;?>           
        }
    }).on('success.form.fv', function(e) {
        e.preventDefault();
        var $form = $(e.target);
        var fv = $form.data('FormDataGral');
            fv.defaultSubmit();
    });   
});