<?php $this->headScript()->appendFile('/js/modules/functionGral.js') ?>  
<?php $this->headScript()->appendFile('/js/modules/main/validatePhones.js') ?>  
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>				
<input type="hidden" id="inputModule" value="<?php echo $this->moduleInfo['SCRIPT']; ?>"/>
<input type="hidden" id="txtResultOk"  value="<?php echo $this->resultOp;?>"/>
<div class="row">
	<div class="col-md-12">
		<ul class="page-breadcrumb breadcrumb">
			<li>
				<i class="fa fa-home"></i>
				<a href="/main/main/inicio">
					Inicio
				</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="<?php echo $this->moduleInfo['SCRIPT'];?>">
					<?php echo $this->moduleInfo['DESCRIPCION'];?>
				</a>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<a href="#">
					Detalle del Teléfono
				</a>
			</li>							
		</ul>
	</div>
</div>


<div class="portlet box blue">
	<div class="portlet-title">
		<div class="caption">
			<i class="fa fa-reorder"></i>Información del usuario
		</div>
		<div class="tools">

		</div>
	</div>
	<div class="portlet-body form">
		<?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
			<div id="divpErrorLogin" class="alert alert-danger alert-dismissable" style="display:block;">
			  <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
			  <h4>Error</h4>
			  <div>Usted no tiene permiso para ver esta información</div>
			</div>						
		<?php else:?>
			<ul class="nav nav-tabs">
				<li class="active"><a data-toggle="tab" href="#tabGral">Información</a></li>
		        <?php if($this->idToUpdate>0):?>
					<li><a href="#tabSecond" data-toggle="tab">Eventos</a></li>
		    	<?php endif;?>	
			</ul>
			<div class="tab-content">					
				<div id="tabGral" class="tab-pane <?php echo (@$this->eventAction) ? '':'active';?> ">							
					<form name="FormData" id="FormData" method="POST" action="<?php echo str_replace('index', 'getinfo', $this->moduleInfo['SCRIPT']); ;?>" class="form-horizontal">
						<input type="hidden" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
				    	<input type="hidden" name="catId"  value="<?php echo $this->catId; ?>" id="catId" />

				    	<?php $sError = ''?>
		            	<?php if(@$this->errors['eIMEI']):?>
		            		<?php $sError = 'imei';?>							
		            	<?php elseif(@$this->errors['status']=='no-insert'):?>
		            		<?php $sError = 'problem';?>
		            	<?php endif;?>	
						<input type="hidden" id="txtErrorType" value="<?php echo $sError;?>"/>
				    	<div class="form-body">
							<div class="form-group">
								<label class="col-md-3 control-label">Marca<span class="required">*</span></label>
								<div class="col-md-4">
									<select class="form-control input-sm" name="inputMarca" id="inputMarca" <?php echo $disabled;?> onChange="getoptionsCbo('Modelo','modelot',this.value,'','');">
										<option value="">Seleccionar una opción</option>
		                                <?php echo $this->marcas;?>
									</select>
								</div>							
							</div>	

							<div class="form-group">
								<label class="col-md-3 control-label">Modelo<span class="required">*</span></label>
								<div class="col-md-4">
									<div id="divModelo">
										<select class="form-control input-sm" name="inputModelo" id="inputModelo"<?php echo $disabled;?> >
											<option value="">Seleccionar una opción</option>
			                                <?php echo $this->modelos;?>
										</select>
									</div>
								</div>							
							</div>	

							<div class="form-group">
								<label class="col-md-3 control-label">Descripción<span class="required">*</span></label>
								<div class="col-md-4">
									<input type="text" name="inputDesc" id="inputDesc" data-required="1" class="form-control" value="<?php echo @$this->data['DESCRIPCION']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
								</div>
							</div>	

							<div class="form-group">
								<label class="col-md-3 control-label">Identificador<span class="required">*</span></label>
								<div class="col-md-4">
									<input type="text" name="inputImei" id="inputImei" data-required="1" class="form-control" value="<?php echo @$this->data['IDENTIFICADOR']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
								</div>
							</div>

							<div class="form-group">
								<label class="col-md-3 control-label">Tel. Fijo</label>
								<div class="col-md-4">
									<input type="text" name="inputTel" id="inputTel" class="form-control" value="<?php echo @$this->data['TELEFONO']; ?>"  <?php echo $disabled;?> autocomplete="off" >	
								</div>
							</div>							

							<div class="form-group">
								<label class="col-md-3 control-label">Usuario Asignado</label>
								<div class="col-md-4 ">
									<input type="hidden" id="inputIdAssign" name="inputIdAssign" value="<?php echo @$this->data['ID_ACTIVO'];?>"/>
									<?php if(@$this->data['ASIGNADO']=='0' || @$this->idToUpdate==-1):?>
										<div class="col-md-9 pand0">
											<input readonly type="text" name="inputSearch" id="inputSearch" class="form-control" value="<?php echo (@$this->data['ASIGNADO']=='0') ? 'Sin Asignar': @$this->data['ASIGNADO'];?>"  <?php echo $disabled;?> autocomplete="off" >	
										</div>
										<div class="col-md-3 ">
											<a class="btn default" data-toggle="modal" href="#static" onclick="openSearch()">
	                                            <i class="fa fa-search icon-white"></i>                                         
	                                        </a>      
										</div>
									<?php else:?>
										<div class="col-md-9 pand0">
											<input readonly type="text" name="inputAsign" class="form-control" value="<?php echo (@$this->data['ASIGNADO']=='0') ? 'Sin Asignar': @$this->data['ASIGNADO'];?>"  <?php echo $disabled;?> autocomplete="off" >	
										</div>
										<div class="col-md-3">										
											<button type="button" id="btnDelRel" class="btn red"><i class="fa fa-times icon-white"></i></button>									
										</div>	
									<?php endif;?>										
								</div>
							</div>								

							<div class="form-group">
								<label class="col-md-3 control-label">Activo<span class="required">*</span></label>
								<div class="col-md-4">
									<select class="form-control input-sm" name="inputEstatus" id="inputEstatus" <?php echo $disabled;?> >
										<option value="">Seleccionar una opción</option>
		                                <?php echo $this->status;?>
									</select>
								</div>
							</div>

						</div>	

						<?php if($disabled!='disabled'):?>
						<div class="form-actions fluid">
							<div class="col-md-offset-3 col-md-9">
								<button type="submit" class="btn blue btnSave">Guardar</button>
								<button type="button" class="btn default" onClick="location.href='<?php echo $this->moduleInfo['SCRIPT']; ?>';">Cancelar</button>
							</div>
						</div>			
						<?php endif;?>						

					</form>
				</div>
				<div id="tabSecond" class="tab-pane <?php echo (@$this->eventAction) ? 'active':'';?>">				



				</div>						
			</div>	
			<!-- END FORM-->
		<?php endif;?>		
	</div>
</div>

<div id="static" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Buscar Usuarios Sin Asignar</h4>
            </div>
            <div class="modal-body">
            	<img id="loader1" class="col-xs-offset-4" src="/images/loading.gif" alt="loading gif"/>
                <iframe class="hmodal550" id="iFrameSearch" src="" style="zoom:0" frameborder="0"></iframe>
            </div>
        </div>
    </div>
</div>  