<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>
<input type="hidden" id="inputShowAlert" value="<?php echo (isset($this->resultOp)) ?  '1': '0'; ?>"/>             
<!-- BEGIN PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN PAGE TITLE & BREADCRUMB-->
            <h3 class="page-title">
            Teléfonos <small>administración</small>
            </h3>
            <!-- END PAGE TITLE & BREADCRUMB-->
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <div id="dErrorAlert" class="alert alert-danger display-hide">
                <button class="close" data-close="alert"></button>
                Al parecer ha ocurrido un error al eliminar el registro, favor de intentar mas tarde.
            </div>          
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        Teléfono
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="reload">
                        </a>
                    </div>
                </div>
                <input type="hidden" id="inputModule" value="<?php echo str_replace('index', 'getinfo', $this->moduleInfo['SCRIPT']); ;?>"/>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <?php if($this->dataUser['INSERTAR']==1): ?>
                        <div class="btn-group">
                            <button id="sample_editable_1_new" class="btn green" onclick="location.href='<?php echo str_replace('index', 'getinfo?catId=-1', $this->moduleInfo['SCRIPT']); ;?>'">
                             Nuevo <i class="fa fa-plus"></i>
                            </button>
                        </div>
                        <?php endif;?>
                        <div class="btn-group pull-right">

                        </div>
                    </div>
                    <table class="table table-striped table-bordered table-hover" id="dataTable">
                        <thead>
                            <tr>                                        
                                <th>Marca</th>
                                <th>Modelo</th>
                                <th>Descripción</th>
                                <th>Teléfono</th>
                                <th>Identificador</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($this->datatTable as $key => $items): ?>  
                            <tr class="odd gradeX">                       
                                <td><?php echo $items['MARCA']; ?></td>
                                <td><?php echo $items['MODELO']; ?></td>
                                <td><?php echo $items['DESCRIPCION']; ?></td>
                                <td><?php echo $items['TELEFONO']; ?></td>
                                <td><?php echo $items['IDENTIFICADOR']; ?></td>
                                <td class="text-center">
                                    <?php if($this->dataUser['LECTURA']==1): ?>
                                        <a href="<?php echo str_replace('index', 'getinfo?catId=', $this->moduleInfo['SCRIPT']).$items['ID_TELEFONO']; ;?>" class="btn blue">
                                            <i class="fa fa-edit"></i>  
                                        </a>                                        
                                    <?php endif;?> 
                                    <?php if($this->dataUser['ELIMINAR']==1): ?>
                                        <a class="btn red" data-toggle="modal" href="#static" onclick="beforeDelete('<?php echo $items['ID_TELEFONO']; ?>')">
                                            <i class="fa fa-times"></i>                                         
                                        </a>                                        
                                    <?php endif;?>
                                </td>
                            </tr>
                            <?php endforeach;?>                         
                    </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>

    <div class="modal fade" id="ajax" role="basic" aria-hidden="true">
        <div class="page-loading page-loading-boxed">
            <img src="/assets/img/loading-spinner-grey.gif" alt="" class="Espere">
            <span>
                &nbsp;&nbsp;Loading...
            </span>
        </div>
        <div class="modal-dialog">
            <div class="modal-content">
            </div>
        </div>
    </div>  

    <div id="static" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title">Atención!</h4>
                </div>
                <div class="modal-body">
                    <p>¿Realmente desea eliminar este registro?</p>
                </div>
                <div class="modal-footer">
                    <input type="hidden" id="inputDelete" value="-1"/>
                    <a type="button" class="btn blue" href="javascript:deleteRow();">Eliminar</a>
                    <button type="button" data-dismiss="modal" class="btn default">Cancelar</button>
                </div>
            </div>
        </div>
    </div>  