
<?php $this->headScript()->appendFile('/js/modules/main/searchActivos.js') ?>	
    <div class="block">
        <div class="block-content collapse in">
                <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
                    <thead>
                        <tr>
                        	<th>Usuario</th>
                            <th>Nombre</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>                                
                        <?php foreach($this->dataTable as $key => $items): ?>  
                        <tr class="odd gradeX">
                            <td><?php echo $items['USUARIO']; ?></td>
                            <td><?php echo $items['NAME']; ?></td>
                            <td class="text-center">    

                                <a href="javascript:parent.assignValue('<?php echo $items['NAME']; ?>',<?php echo $items['ID_USUARIO'];?>)"><button class="btn btn-primary"> <i class="fa fa-arrow-circle-o-down icon-white"></i></button></a>
                            </td>
                        </tr>    
                        <?php endforeach;?>                                             
                    </tbody>
                </table>
        </div>
    </div>
    <!-- /block -->