<?php //$this->headScript()->appendFile('/assets/js/fullcalendar/fullcalendar.js') ?>
<?php //$this->headScript()->appendFile('/js/modules/dashboard/jsCalendarDates.js') ?>

<?php $this->headLink()->appendStylesheet('/libs/gantt/css/style.css');?>
<?php $this->headScript()->appendFile('/libs/gantt/js/jquery.fn.gantt.js') ?>
<?php $this->headScript()->appendFile('/js/modules/dashboard/jsDashboardGantt.js'); ?>

<?php $aLast = strtotime(date('Y-m-d', strtotime('-30 day'))) ;?>
<?php $aNext = strtotime(date('Y-m-d', strtotime('+30 day'))) ;?>
<?php $aNext = str_pad($aNext,13,"0",STR_PAD_RIGHT);?>
<?php $aLast = str_pad($aLast,13,"0",STR_PAD_RIGHT);?>

<?php $this->headScript()->captureStart() ?>
    adataSource = [
        <?php $iSucursal = -1;?>
        <?php foreach($this->aData as $key => $items):?>
            <?php if($iSucursal!=$items['ID_SUCURSAL']):?>
                <?php $sNameSuc  = $items['N_SUCURSAL'];?>
                <?php $iSucursal = $items['ID_SUCURSAL'];?>         
            <?php else:?>
                <?php $sNameSuc  = '';?>
            <?php endif;?>
            {
                name: "<?php echo ($this->iCinstalac==-1) ? $sNameSuc : $items['N_TECNICO'];?>",
                desc: "<?php echo ($this->iCinstalac==-1) ? $items['N_TECNICO'] : '';?>",               
                values: [<?php foreach($items['citas'] as $key => $itemDates):?>{
                            from: "/Date(<?php echo $itemDates['fechaSin'];?>)/",
                            to: "/Date(<?php echo $itemDates['fechaSfin'];?>)/",
                            label: "<?php echo $itemDates['FOLIO'];?>",
                            desc: "<?php echo "Cliente: ".$itemDates['RAZON_SOCIAL']."</br>".
                                               "Fecha: ".$itemDates['FECHA_CITA']."</br>".
                                               "Hora : ".$itemDates['HORA_CITA']."</br>".
                                               "Folio: ".$itemDates['FOLIO']."</br>".
                                               "Estatus: ".$itemDates['N_ESTATUS']."</br>";?>",
                            customClass: "ganttCode_<?php echo $itemDates['ID_ESTATUS'];?>",
                            dataObj: <?php echo $itemDates['ID_CITA'];?>,
                        },<?php endforeach;?>]
            },
        <?php endforeach;?>
    ];
<?php $this->headScript()->captureEnd(); ?>    
    <div id="divBodyPage" class="page-body">
        <div class="widget">
            <div class="widget-header ">
                <span class="widget-caption">Actividades del Personal</span>
                <div class="widget-buttons">
                    <a href="#" data-toggle="maximize">
                        <i class="fa fa-expand"></i>
                    </a>
                    <a href="#" data-toggle="collapse">
                        <i class="fa fa-minus"></i>
                    </a>
                </div>
            </div>
            <div class="widget-body">
                <div class="row">
                    <div class="col-md-5 col-xs-5 col-sm-5">
                        <form method="POST" action="/dashboard/gantt/index?action=today" id="FormData" class="form-horizontal formcustom">
                            <input type="hidden" name="optReg" value="search" />
                            <div class="span10">
                                <div class="col-md-4">
                                    <label>Sucursal</label>
                                </div>
                                <div class="col-md-8">
                                    <select class="chzn-select col-md-12" id="inputSucursal" name="inputSucursal" onChange="submitForm();">
                                        <option value="-1">Todos</option>
                                        <?php echo $this->cInstalaciones;?>
                                    </select>
                                </div>
                            </div>                      
                        </form>
                    </div>                    
                    <div class="pull-right col-md-5">
                        <div class="desStatus">
                            <table>
                                <?php $control = 0;?>
                                <?php foreach($this->aEstatus as $key => $items):?>
                                    <?php if($control==0):?>
                                        <tr>
                                    <?php endif;?>
                                    <td>
                                        <div style="width:10px;height:10px;background-color:<?php echo $items['COLOR'];?>;"></div>
                                    </td>
                                    <td> <?php echo $items['NAME'];?></td>
                                    <?php $control++;?>

                                    <?php if($control==7):?>
                                        </tr>           
                                        <?php $control=0;?>                         
                                    <?php endif;?>
                                <?php endforeach;?>
                            </table>
                        </div>    
                    </div>                    

                </div>
                <div class="gantt"></div>   
            </div>
        </div>
    </div>