<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>
<!-- BEGIN PAGE HEADER-->
	<div class="row">
		<div class="col-md-12">
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">
			Perfiles <small>administración MI EJEMPLO</small>
			</h3>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
			<div id="dErrorAlert" class="alert alert-danger display-hide">
				<button class="close" data-close="alert"></button>
				Al parecer ha ocurrido un error al eliminar el registro, favor de intentar mas tarde.
			</div>			
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption">
						Perfiles
					</div>
					<div class="tools">
						<a href="javascript:;" class="reload">
						</a>
					</div>
				</div>
				<input type="hidden" id="inputModule" value="<?php echo str_replace('index', 'getinfo', $this->moduleInfo['SCRIPT']); ;?>"/>
				<div class="portlet-body">
					<div class="table-toolbar">
						<?php if($this->dataUser['INSERTAR']==1): ?>
						<div class="btn-group">
							<button id="sample_editable_1_new" class="btn green" onclick="location.href='<?php echo str_replace('index', 'getinfo?catId=-1', $this->moduleInfo['SCRIPT']); ;?>'">
							 Nuevo <i class="fa fa-plus"></i>
							</button>
						</div>
						<?php endif;?>
						<div class="btn-group pull-right">
							<!--
							<button class="btn dropdown-toggle" data-toggle="dropdown">Opciones <i class="fa fa-angle-down"></i>
							</button>
							<ul class="dropdown-menu pull-right">
								<li>
									<a href="#">
										 Imprimir
									</a>
								</li>
								<li>
									<a href="#">
										 Exportar PDF
									</a>
								</li>
								<li>
									<a href="#">
										 Exportar Excel
									</a>
								</li>
							</ul>
							-->
						</div>
					</div>
					<table class="table table-striped table-bordered table-hover" id="dataTable">
                        <thead>
                            <tr>                                        
                                <th>ID</th>
                                <th>Descripción</th>                                
                                <th>Opciones</th>
                            </tr>
                        </thead>
						<tbody>
                            <?php foreach($this->datatTable as $key => $items): ?>  
                            <tr class="odd gradeX">                                        
                                <td style="width:50px"><?php echo $items['ID_PERFIL']; ?></td>
                                <td><?php echo $items['DESCRIPCION']; ?></td>
                                <td class="text-center" style="width:100px">
                                    <?php if($this->dataUser['LECTURA']==1): ?>
										<a href="/users/profiles/getinfo?catId=<?php echo $items['ID_PERFIL']; ?>" class="btn blue">
											<i class="fa fa-edit"></i>	
										</a>                                    
                                    <?php endif;?> 
                                    <?php if($this->dataUser['ELIMINAR']==1): ?>
	                                    <a class="btn red" data-toggle="modal" href="#static" onclick="beforeDelete('<?php echo $items['ID_PERFIL']; ?>')">
	                                    	<i class="fa fa-times"></i>											
										</a>
                                    <?php endif;?>
                                </td>
                            </tr>    
                            <?php endforeach;?>							
					</tbody>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>

	<div class="modal fade" id="ajax" role="basic" aria-hidden="true">
		<div class="page-loading page-loading-boxed">
			<img src="/assets/img/loading-spinner-grey.gif" alt="" class="Espere">
			<span>
				&nbsp;&nbsp;Loading...
			</span>
		</div>
		<div class="modal-dialog">
			<div class="modal-content">
			</div>
		</div>
	</div>	

	<div id="static" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					<h4 class="modal-title">Atención!</h4>
				</div>
				<div class="modal-body">
					<p>¿Realmente desea eliminar este registro?</p>
				</div>
				<div class="modal-footer">
					<input type="hidden" id="inputDelete" value="-1"/>
					<a type="button" class="btn blue" href="javascript:deleteRow();">Eliminar</a>
					<button type="button" data-dismiss="modal" class="btn default">Cancelar</button>
				</div>
			</div>
		</div>
	</div>	