<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/js/reports/jsReportInfo.js') ?>
<input type="hidden" id="istatus" value="<?php echo $this->iStatus?>"/>	
	<!-- /Page Header -->
    <div class="page-header position-relative">
        <div class="header-title">
            <h1>
                Reportes
            </h1>
            <!--<small>Detalle de la Cita</small>-->
        </div>
        <div class="header-buttons">

        </div>
    </div>    
    <!-- /Page Header -->
    <!-- Page Body -->
    <div class="page-body">
        <div class="col-xs-12 col-md-12">
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-xs-12">
                    <div class="well invoice-container">
                        <div class="row">
                            <div class="col-xs-6">
                                <h3 class="">
                                    <!--<i class="fa fa-check"></i>-->
                                    Detalle de la Cita
                                </h3>

                            </div>
                            <div class="col-xs-6 text-right">
                                <h1>
                                    <img src="/assets/img/logo.png" alt="" style="width:200px; height:45px; margin-right:-17px" />
                                </h1>
                                <div>
                                    <span>Folio:</span>
                                    <span>#<?php echo @$this->aData['FOLIO'];?></span>
                                    <span> | </span>
                                    <span>Fecha y Hora:</span>
                                    <span><?php echo @$this->aData['FECHA_CITA']." ".@$this->aData['HORA_CITA'] ;?></span>
                                    <span> | </span>
                                    <a href="#">
                                        <i class="glyphicon glyphicon-print carbon"></i>
                                    </a>
                                </div>
                                <div class="horizontal-space"></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h6>Información de la Cita</h6>
                                    </div>
                                    <div class="panel-body">
                                        <table class="col-md-12">
                                            <tr>
                                                <th>Tipo de Cita</th><td><?php echo @$this->aData['N_TIPO'];?></td>
                                            </tr>
                                            <tr>
                                                <th>Cliente </th><td><?php echo @$this->aData['NOMBRE_COMPLETO']." ".@$this->aData['RAZON_SOCIAL'];?></td>
                                            </tr>
                                            <tr>
                                                <th>Contacto</th><td><?php echo @$this->aData['CONTACTO'];?></td>
                                            </tr>
                                            <tr>
                                                <th>Tel. Contacto</th><td><?php echo @$this->aData['TELEFONO_CONTACTO'];?></td>
                                            </tr>                                            
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <h6>Detalle de la Cita</h6>
                                    </div>
                                    <div class="panel-body">
                                        <table class="col-md-12">
                                            <tr>
                                                <th>Fecha Arribo:</th><td><?php echo (isset($this->aData['FECHA_ARRIBO'])) ? $this->aData['FECHA_ARRIBO'] : '--';?></td>
                                            </tr>
                                            <tr>
                                                <th>Fecha Inicio:</th><td><?php echo (isset($this->aData['FECHA_INICIO'])) ? $this->aData['FECHA_INICIO'] : '--';?></td>
                                            </tr>
                                            <tr>
                                                <th>Fecba Fin:</th><td><?php echo (isset($this->aData['FECHA_FIN'])) ? $this->aData['FECHA_FIN'] : '--';?></td>
                                            </tr>
                                            <tr>
                                                <th>Personal Atendio:</th><td><?php echo @$this->aData['NOMBRE_COMPLETO'];?></td>
                                            </tr>                                            
                                        </table>
                                    </div>
                                </div>
                            </div>                            
                            <div class="col-xs-4">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        Lugar de la Cita
                                    </div>
                                    <div class="panel-body no-padding">
                                        <input type="hidden" id="inputLatitud"  name="inputLatitud"  value="<?php echo @$this->aDataLocation['LATITUD'];?>"/>
                                        <input type="hidden" id="inputLongitud" name="inputLongitud" value="<?php echo @$this->aDataLocation['LONGITUD'];?>"/>
                                        <div id="map" style="height:100px;width:100%;"></div>                                        
                                        <small><?php echo @$this->aDataLocation['CALLE'];?>,
                                        <?php echo @$this->aDataLocation['COLONIA'];?>,
                                        <?php echo @$this->aDataLocation['MUNICIPIO'];?>,
                                        <?php echo @$this->aDataLocation['ESTADO'];?>,
                                        CP:<?php echo @$this->aDataLocation['CP'];?></small>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-6">
                                <h3 class="">                                  
                                    Información Registrada
                                </h3>
                            </div>                            
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                
                                    <div class="tabbable tabs-left">
                                        <ul class="nav nav-tabs" id="myTab3">
                                            <?php $controlTab=0;?>
                                            <?php foreach(@$this->aFormluarios as $key => $items):?>
                                                <li class="<?php echo ($controlTab==0)  ? 'active': '';?> tab-blue">
                                                    <a data-toggle="tab" href="#tab_<?php echo $items['ID_FORMULARIO']; ?>">
                                                        <?php echo $items['ORDEN']." - ".$items['TITULO']; ?>
                                                    </a>
                                                </li>
                                                <?php $controlTab++;?>
                                            <?php endforeach;?>
                                        </ul>

                                        <div class="tab-content">
                                            <?php $controlTab=0;?>
                                            <?php foreach(@$this->aFormluarios as $key => $items):?>
                                                <div id="tab_<?php echo $items['ID_FORMULARIO']; ?>" class="tab-pane in <?php echo ($controlTab==0)  ? 'active': '';?>">
                                                    <div class="">
                                                        <div class="col-md-8 col-sm-8">
                                                            <table  class="table table-striped table-hover table-bordered">
                                                                <?php foreach($items['result'] as $key => $aresults):?>
                                                                    <tr>
                                                                        <?php if($aresults['ID_TIPO']=="8"): ?>
                                                                            <td colspan="2" class="text-center"><b><?php echo $aresults['DESCRIPCION'];?></b></td>
                                                                        <?php else: ?>
                                                                            <td class="col-md-6"><b><?php echo $aresults['DESCRIPCION'];?></b></td>
                                                                            <td><?php echo (isset($aresults['CONTESTACION'])) ? $aresults['CONTESTACION'] : '--';?></td>
                                                                        <?php endif;?>   
                                                                    </tr>
                                                                <?php endforeach;?>
                                                            </table>
                                                        </div>
                                                        <div class="col-md-4 col-sm-4">
                                                            <?php $controlMedia = 0;?>
                                                            <?php foreach($items['result'] as $key => $aresults):?>
                                                                <tr>
                                                                    <?php if($aresults['ID_TIPO']=="9" || $aresults['ID_TIPO']=="10"): ?>
                                                                        <td colspan="2" class="text-center"><b><?php echo $aresults['DESCRIPCION'];?></b></td>
                                                                    <?php endif;?>
                                                                </tr>
                                                            <?php endforeach;?>
                                                            <?php if($controlMedia==0):?>
                                                                <div class="col-md-12 text-center">
                                                                    <img class="col-md-12 col-sm-12" src="/assets/img/no-media.png" />
                                                                    <h4>No hay información multimedia</h4>
                                                                </div>
                                                            <?php endif;?>
                                                        </div>
                                                    </div>                                                    
                                                </div>
                                                <?php $controlTab++;?>
                                            <?php endforeach;?>
                                        </div>
                                    </div>
                                    <div class="horizontal-space"></div>
                            </div>                            
                        </div>                        
                    </div>
                </div>
            </div>
    	</div>
	</div>