<?php $this->headScript()->appendFile('/js/modules/gralTables.js') ?>
<?php $partes = explode("|",$this->colorES);?>
<!-- BEGIN PAGE HEADER-->
	<div class="row">
		<div class="col-md-12">
	       <!-- BEGIN PAGE TITLE & BREADCRUMB-->
		 	  <h3 class="page-title">
			  Detalles <small><?php echo $partes[1]?></small>
			  </h3>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
	<!-- END PAGE HEADER-->
	
    <!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-12">
					
			<!-- BEGIN EXAMPLE TABLE PORTLET-->
			<div class="portlet box <?php echo $partes[0];?>">
				<div class="portlet-title">
					<div class="caption">
						datos
					</div>
					<div class="tools">
						<a href="javascript:;" class="reload">
						</a>
					</div>
				</div>
				
				<div class="portlet-body">
					<div class="table-toolbar">
						
						<div class="btn-group pull-right">
							<!--
							<button class="btn dropdown-toggle" data-toggle="dropdown">Opciones <i class="fa fa-angle-down"></i>
							</button>
							<ul class="dropdown-menu pull-right">
								<li>
									<a href="#">
										 Imprimir
									</a>
								</li>
								<li>
									<a href="#">
										 Exportar PDF
									</a>
								</li>
								<li>
									<a href="#">
										 Exportar Excel
									</a>
								</li>
							</ul>
							-->
						</div>
					</div>
					<table class="table table-striped table-bordered table-hover" id="dataTable">
                        <thead>
                            <tr>                                        
                                <th>ID</th>
                                <th>Descripción</th>                                
                                <th>Opciones</th>
                            </tr>
                        </thead>
						<tbody>
                            <?php for($r=0;$r<10;$r++){ ?>  
                            <tr class="odd gradeX">                                        
                                <td style="width:50px"><?php echo $r; ?></td>
                                <td> hi</td> 
                                <td> hidssds</td>                                 
                            </tr>    
                            <?php }?>							
					</tbody>
					</table>
				</div>
			</div>
			<!-- END EXAMPLE TABLE PORTLET-->
		</div>
	</div>

	<div class="modal fade" id="ajax" role="basic" aria-hidden="true">
		<div class="page-loading page-loading-boxed">
			<img src="/assets/img/loading-spinner-grey.gif" alt="" class="Espere">
			<span>
				&nbsp;&nbsp;Loading...
			</span>
		</div>
		<div class="modal-dialog">
			<div class="modal-content">
			</div>
		</div>
	</div>	

	<div id="static" class="modal fade" tabindex="-1" data-backdrop="static" data-keyboard="false">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
					<h4 class="modal-title">Atención!</h4>
				</div>
				<div class="modal-body">
					<p>¿Realmente desea eliminar este registro?</p>
				</div>
				<div class="modal-footer">
					<input type="hidden" id="inputDelete" value="-1"/>
					<a type="button" class="btn blue" href="javascript:deleteRow();">Eliminar</a>
					<button type="button" data-dismiss="modal" class="btn default">Cancelar</button>
				</div>
			</div>
		</div>
	</div>	