<?php $this->headScript()->appendFile('/js/modules/dashboard/dashboard.js') ?>
			<!-- BEGIN PAGE HEADER-->
			<div class="row">
				<div class="col-md-12">
					<!-- BEGIN PAGE TITLE & BREADCRUMB-->
					<h3 class="page-title">
					Dashboard 
					</h3>
					<ul class="page-breadcrumb breadcrumb">
						<li>
							<i class="fa fa-home"></i>
							<a href="index.html">
								Inicio
							</a>
							<i class="fa fa-angle-right"></i>
						</li>
						<li>
							<a href="#">
								Dashboard
							</a>
						</li>
						<li class="pull-right">
							<div id="dashboard-report-range" class="dashboard-date-range tooltips" data-placement="top" data-original-title="Change dashboard date range">
								<i class="fa fa-calendar"></i>
								<span>
								</span>
								<i class="fa fa-angle-down"></i>
							</div>
						</li>
					</ul>
					<!-- END PAGE TITLE & BREADCRUMB-->
				</div>
			</div>
			<!-- END PAGE HEADER-->
            
			<!-- BEGIN DASHBOARD COMPONENTES -->
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat <?php echo $this->componente['COLOR_TIEMPO_ENCENDIDO'];?>">
						<div class="visual">
							<i  <?php echo $this->componente['ICONO_ENCENDIDO'];?>></i>
						</div>
						<div class="details">
							<div class="number">
								 <?php echo $this->componente['TIEMPO_ENCENDIDO'];?>
							</div>
							<div class="desc">
								 Tiempo Encendido
							</div>
						</div>
						<!--<a class="more" href="#" onclick="verDetalles('green','TIEMPO_ENCENDIDO');">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>-->
                        <a class="more" href="#" onclick="verStatus(1);">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
				
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat <?php echo $this->componente['COLOR_APAGADO'];?>">
						<div class="visual">
							<i  <?php echo $this->componente['ICONO_APAGADO'];?>></i>
						</div>
						<div class="details">
							<div class="number">
								 <?php echo $this->componente['TIEMPO_APAGADO'];?>
							</div>
							<div class="desc">
								 Tiempo Apagado
							</div>
						</div>
						<!--<a class="more" href="#" onclick="verDetalles('red','TIEMPO_APAGADO');">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>-->
                          <a class="more" href="#" onclick="verStatus(3);">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
                
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat <?php echo $this->componente['COLOR_TIEMPO_SIN_REPORTAR'];?>">
						<div class="visual">
							<i  <?php echo $this->componente['ICONO_SIN_REPORTAR'];?>></i>
						</div>
						<div class="details">
							<div class="number">
								 <?php echo $this->componente['TIEMPO_SIN_REPORTAR'];?>
							</div>
							<div class="desc">
								Tiempo sin reportar
							</div>
						</div>
						<!--<a class="more" href="#" onclick="verDetalles('yellow','TIEMPO_SIN_REPORTAR');">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>-->
                          <a class="more" href="#" onclick="verStatus(2);">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
                
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
					<div class="dashboard-stat <?php echo $this->componente['COLOR_TIEMPO_X_SIN_REPORTAR'];?>">
						<div class="visual">
							<i  <?php echo $this->componente['ICONO_X_SIN_REPORTAR'];?>></i>
						</div>
						<div class="details">
							<div class="number">
								 <?php echo $this->componente['TIEMPO_X_SIN_REPORTAR'];?>
							</div>
							<div class="desc">
								Tiempo X sin reportar
							</div>
						</div>
						<!--<a class="more" href="#" onclick="verDetalles('purple','TIEMPO_X_SIN_REPORTAR');">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>-->
                          <a class="more" href="#" onclick="verStatus(4);">
							 Detalles <i class="m-icon-swapright m-icon-white"></i>
						</a>
					</div>
				</div>
			</div>
          	<!-- END DASHBOARD COMPONENTES -->
