<?php $this->headLink()->appendStylesheet('/assets/plugins/bootstrap-modal/css/bootstrap-modal.css') ?>
<?php $this->headLink()->appendStylesheet('/assets/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css') ?>
<?php $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false') ?>
<?php $this->headScript()->appendFile('/assets/scripts/custom/components-jqueryui-sliders.js'); ?> 
<?php $this->headScript()->appendFile('/assets/plugins/select2/select2.min.js'); ?> 
<?php $this->headScript()->appendFile('/assets/plugins/data-tables/jquery.dataTables.js'); ?> 
<?php $this->headScript()->appendFile('/assets/plugins/data-tables/DT_bootstrap.js'); ?> 
<?php $this->headScript()->appendFile('/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js'); ?>
<?php $this->headScript()->appendFile('/assets/plugins/bootstrap-modal/js/bootstrap-modal.js'); ?>
<?php $this->headScript()->appendFile('/assets/scripts/custom/ui-extended-modals.js'); ?>
<?php $this->headScript()->appendFile('/js/jquery.countdown360.js'); ?> 
<?php $this->headScript()->appendFile('/js/modules/location/rastreotels.js'); ?>
<?php $control=0?>
<div id="divDataPersonal" class="hide"><?php foreach($this->aPersonal as $key => $items):?><?php echo ($control==0) ? '': '?';?><?php echo $items['ID']."|".$items['NAME']."|".$items['ID_SUCURSAL'];?><?php $control++;?><?php endforeach;?>
</div>
<!-- BEGIN PAGE HEADER-->
	<div class="row">
		<div class="col-md-12">
			<!-- BEGIN PAGE TITLE & BREADCRUMB-->
			<h3 class="page-title">
			Rastreo <small>Localización de Teléfonos</small>
			</h3>
			<!-- END PAGE TITLE & BREADCRUMB-->
		</div>
	</div>
	<!-- END PAGE HEADER-->
	<!-- BEGIN PAGE CONTENT-->
	<div class="row">
		<div class="col-md-4">
			<div class="portlet box blue">
				<div class="portlet-title">
					<div class="caption">
						Teléfonos
					</div>
				</div>
				<div class="portlet-body row-min-h470">
					<h3 class="page-title pull-right">
						<small>
						Sucursal					
							<select class="chzn-select" id="cboInstalacion" name="cboInstalacion" onChange="drawSelectPersonal(this.value);">
								<option value="">Seleccionar una opción</option>
								<?php echo $this->cInstalaciones;?>
							</select>
						</small>
					</h3>
					<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="dataTable">
		                <thead>
		                    <tr>
		                        <th style="width:10px;"><input type="checkbox" name="inputAllCheck" id="inputAllCheck" onClick="optionAll(this.checked);"/></th>
		                        <th>Teléfono</th>
		                        <th style="width:95px"></th>
		                    </tr>
		                </thead>
		                <tbody>                                
		                    
		                </tbody>
		            </table>
				</div>
			</div>				
		</div>
		<div class="col-md-8">
			<div class="portlet box blue ">
				<div class="portlet-title">
					<div class="caption">
						Mapa
					</div>
				</div>
				<div class="portlet-body">
		            <div id="Map" style="width:100%;height:420px;">

		            </div>  
		            <div class="row">
		            	<div id="countdown" ></div>
						<div id="divSliderC" style="display:none;" class="block-content collapse in col-md-12">
							<div class="col-md-4">
								<div class="slider-snap-inc slider">Intervalo de Actualización <b>								
									<span id="slider-snap-inc-amount"></span> segs.								
								</b></div>
							</div>							
							<div id="slider-snap-inc" class="slider bg-blue col-md-7">
							</div>
						</div>                    
		            </div> 							
				</div>
			</div>				
		</div>
	</div>	

	<div id="ajax-modal" class="modal fade" tabindex="-1"></div>