<?php $this->headScript()->appendFile('/js/modules/location/rastreotels.js') ?>  	
	<input type="hidden" id="istatus" value="<?php echo $this->iStatus?>"/>	
	<!-- /Page Header -->
    <div class="page-header position-relative">
        <div class="header-title">
            <h1>
                Rastreo
            </h1>
            <small>Localización de Teléfonos</small>
        </div>
        <!--Header Buttons-->
        <div class="header-buttons">

        </div>
        <!--Header Buttons End-->
    </div>
    <!-- /Page Header -->
    <!-- Page Body -->
    <div class="page-body">
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="widget">
                    <div class="widget-header ">
                        <span class="widget-caption"></span>
                        <div class="widget-buttons">
                            <a href="#" data-toggle="maximize">
                                <i class="fa fa-expand"></i>
                            </a>
                            <a href="#" data-toggle="collapse">
                                <i class="fa fa-minus"></i>
                            </a>
                        </div>
                    </div>
                    <div class="widget-body">
				        <div class="row">
				            <div class="col-xs-12 col-md-12">
				            	<div class="col-md-8">
									<ul class="mix-filter">										
										<li id="liAll" class="filter btn" data-filter="all" onClick="selectableOptions('divcontentvisible');">
											 Todos
										</li>
										<li id="li1"  class="filter btn btn-palegreen " data-filter="catEncendido"  onClick="selectableOptions('catEncendido');">
											Encendidos
										</li>
										<li id="li2"  class="filter btn  btn-purple" data-filter="catApagado"  onClick="selectableOptions('catApagado');">
											Apagados
										</li>
										<li id="li3"  class="filter btn btn-darkorange  " data-filter="catNoReporte"  onClick="selectableOptions('catNoReporte');">
											 Sin reportar
										</li>
										<li id="li4"  class="filter btn btn-yellow" data-filter="catXsinReporte"  onClick="selectableOptions('catXsinReporte');">
											 Más de 24 hrs sin Reportar
										</li>
									</ul>				            		
				            	</div>
								<?php if(@$this->dataUser['VISUALIZACION']==2): ?>
								<div class="col-md-4">
									<div class="pull-right">							
										<small>Seleccione una Sucursal:</small>
										<form method="POST" action="/location/main/index" id="FormData" class="form-horizontal formcustom">
											<input type="hidden" name="optReg" value="search" />								
											<select class="chzn-select" id="cboInstalacion" name="cboInstalacion" onChange="filterSearch(this.value);">
												<option value="-1">Seleccionar una opción</option>
												<?php echo $this->cInstalaciones;?>
											</select>
										</form>	
									</div>				
								</div>
								<?php endif;?>	
				            </div>
				        </div>
				        <div class="horizontal-space"></div>
						<div class="row">
				            <div class="col-xs-12 col-md-12">				        
								<div class="row p-bottom  ">
									<?php $control=0;?>
									<?php foreach($this->aLastPositions as $items):?>
										<?php if($control==4):?>
											</div>
											<div class="row p-bottom">
											<?php $control=0; ?>
										<?php else:?>
											<?php $control++; ?>
										<?php endif;?>
										<div class="divcontentvisible col-lg-3 col-sm-6 col-xs-12 center-text <?php echo $items['STATREP'];?>">
	                                        <div class="well with-header with-footer center-text" style="background: transparent url(http://maps.googleapis.com/maps/api/staticmap?center=<?php echo $items['LATITUD']?>,<?php echo $items['LONGITUD']?>&zoom=17&size=315x215&sensor=true_or_false&markers=icon:http://tinyurl.com/qfbutda%26chld=cafe%7size:small%7C<?php echo $items['LATITUD']?>,<?php echo $items['LONGITUD']?>) no-repeat top; height: 200px; width:100%;margin-bottom: 0 !important;" >
	                                            <div class="header center-text <?php echo $items['STATCOLOR'];?>"><?php  echo $items['NAME'];?></div>
	                                            <div class="image-map"> </div>
	                                            <div class="footer_custom center-text ">
	                                            	<a href="javascript:goToReport(<?php echo $items['ID'];?>);" class="btn btn-default btn-lg shiny col-md-12">
														 <?php echo $items['FECHA_GPS'];?>
													</a> </div>
	                                        </div>
	                                    </div>									
									<?php endforeach;?>
								</div>
				            </div>
				        </div>
                    </div>
                </div>    
            </div>
        </div>
    </div>