
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title">Ajax Content</h4>
</div>
<div class="modal-body">
	<div class="row">
		<div class="col-md-12">
			<h4>Some Input</h4>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
			<p>
				<input type="text" class="col-md-12 form-control">
			</p>
		</div>
	</div>
</div>
<div class="modal-footer">
	<button type="button" class="btn default" data-dismiss="modal">Close</button>
	<button type="button" class="btn blue">Save changes</button>
</div>
<!--
<div class="modal-body">
	<div class="row customform bg-white ">
		<form method="POST" action="/location/main/reporte?strInput=<?php echo $this->data['strInput']; ?>" id="FormData" class="form-horizontal formcustom">
			<input type="hidden" name="optReg" value="search" />
			<input type="hidden" id="strInputRep" name="strInputRep" value="<?php echo $this->data['strInput']; ?>" />	
				<div class="row row-margin-left25">
					<div class="col-md-5">
						<div class="control-group">
							<label class="control-label col-md-4">Fecha Inicio<span class="required">*</span></label>
							<div class="controls col-md-6">
								<input readonly id="inputFechaIn" name="inputFechaIn" data-required="1"  type="text" class="form-control" value="<?php echo @$this->data['inputFechaIn']; ?>">
							</div>
						</div>				
					</div>
					<div class="col-md-5">
						<div class="control-group">
							<label class="control-label col-md-4">Fecha Fin<span class="required">*</span></label>
							<div class="controls col-md-6">
								<input readonly type="text" id="inputFechaFin" name="inputFechaFin" class="form-control" value="<?php echo (@$this->data['inputFechaFin']); ?>">							
							</div>
						</div>							
					</div>
					<div class="col-md-2">
						<div class="">
							<button type="button" class="btn btn-primary" onClick="obtainReport()">Buscar</button>
						</div>						
					</div>													
				</div>
											
		</form>
	</div>  	
	<div class="customform bg-white row-min-h350">
		<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
		    <li class="active"><a href="#maptab" data-toggle="tab">Mapa</a></li>
		    <li><a href="#tabular" data-toggle="tab">Tabular</a></li>
		</ul>
		<div id="my-tab-content" class="tab-content">	
		    <div class="tab-pane active" id="maptab">
		    	<div id="MapReport" style="width:98%;height:420px;"></div>
		    </div> 

		    <div class="tab-pane" id="tabular">
				<div class="button-excel-15">
					<?php if(count($this->aRecorrido)>0): ?>
						<div class="btn-group">
						 <a target="_blank" href="/location/main/exportsearch?strInput=<?php echo $this->data['strInput']; ?>&inputFechaIn=<?php echo @$this->data['inputFechaIn'];?>&inputFechaFin=<?php echo @$this->data['inputFechaFin'];?>"><button class="btn btn-success"> Exportar <i class="icon-file icon-white"></i></button></a>
						</div>
					<?php endif;?>
		        </div>
				<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered"  id="dataTableRep">
					<thead>				
					    <tr>
					        <th>Fecha GPS</th>
					        <th>Tipo</th>
					        <th>Evento</th>
					        <th>Latitud</th>
					        <th>Longitud</th>
					        <th>Velocidad</th>
					        <th>Bateria</th>
					        <th>Ubicaci√≥n</th>
					    </tr>
					</thead>
					<tbody>
						<?php $result = '';?>
						<?php foreach($this->aRecorrido as $key => $items): ?>
							<tr>
								<td><?php echo $items['FECHA_TELEFONO'];?></td>
								<td><?php echo $items['TIPO_GPS'];?></td>
								<td><?php echo $items['EVENTO'];?></td>
								<td><?php echo $items['LATITUD'];?></td>
								<td><?php echo $items['LONGITUD'];?></td>
								<td><?php echo round($items['VELOCIDAD'],2);?> kms/h.</td>
								<td><?php echo round($items['NIVEL_BATERIA'],2);?> %</td>
								<td><?php echo $items['UBICACION'];?></td>
							</tr>

							<?php $result .= ($result!="") ? "!" : "";?>
							<?php $result .= $items['ID_TELEFONO']."|".
											 $items['FECHA_TELEFONO']."|".
											 $items['TIPO_GPS']."|".
											 $items['EVENTO']."|".
											 $items['LATITUD']."|".
											 $items['LONGITUD']."|".
											 round($items['VELOCIDAD'],2)."|".
											 round($items['NIVEL_BATERIA'],2)."|".
											 $items['UBICACION'];?>
						<?php  endforeach;?>
					</tbody>
				</table>
				<div id="positionsRep" class="hide"><?php echo $result; ?></div>    	
		    </div>
		</div>
	</div>
</div>-->