<?php $this->headScript()->appendFile('/assets/js/nestable/jquery.nestable.min.js') ?> 
<?php $this->headScript()->appendFile('/js/modules/forms/jsValidateForms.js') ?> 
<?php $this->headScript()->appendFile('/js/modules/functionGral.js') ?> 
<?php $disabled = ($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==1) ? 'disabled':'';?>	
<?php $urlActions = ($this->DbmanInfo['CUSTOM_ACTIONS']==1) ? $this->DbmanInfo['CUSTOM_URL'] : '/dbman/main/getdatainfo?ssIdource='.$this->DbmanInfo['CLAVE_MODULO']; ?>
<input type="hidden" id="inputModule" value="<?php echo $this->moduleInfo['SCRIPT']; ?>"/>
    <div class="page-header position-relative">
        <div class="header-title">
            <h1>
                <?php echo $this->DbmanInfo['TITULO']; ?>
            </h1>
            <small>administración</small>
        </div>        
        <div class="pull-right">
            <a class="btn default" name="back" type="button" href="/dbman/main/index?ssIdource=mforms&action=tablegral"><i class="fa fa-angle-left"></i> Regresar</a>           
        </div>        
    </div>
     <!--/Page Header -->     
    <div id="divBodyPage" class="page-body">
        <?php if($this->dataUser['EDITAR']==0 && $this->dataUser['LECTURA']==0): ?>
            <div class="alert alert-block alert-danger fade in block-inner">
                <h6><i class="icon-cancel-circle"></i> Error</h6>
                <hr>
                <p>Usted no tiene permiso para ver esta información.</p>
            </div>
        <?php else:?>


        <div class="row">    
            <?php if(@$this->errors['errorAction']):?>
                <div class="alert alert-block alert-danger fade in block-inner">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h6><i class="icon-cancel-circle"></i><strong>¡Error!</strong> Se han encontrado uno ó mas problemas para guardar la información</h6>
                    <hr>
                    <p>
                        <?php if(count($this->aErrorFields)>0):?>
                        <br/>
                            <strong>Errores:</strong><br/>
                            <?php for($i=0;$i<count($this->aErrorFields);$i++):?>
                                <?php echo $this->aErrorFields[$i]['MessageError'];?><br/>
                            <?php endfor;?>                       
                        <?php endif;?>    
                    </p>
                </div>
            <?php endif;?>          
            <div id="divInfo" class="col-md-12">
                <div id="divForm" class="widget radius-bordered">
                    <div class="widget-header bg-blue">
                        <span class="widget-caption">Información</span>
                    </div>
                    <div class="widget-body padding-5">
                        <form id="formDbman" class="form-horizontal" role="form" method="POST" action="<?php echo $urlActions;?>" <?php echo ($this->DbmanInfo['INCLUYE_ARCHIVOS']==1) ? 'enctype="multipart/form-data"' :'';?>>                                
                            <input type="hidden" id="catId" name="catId"  value="<?php echo $this->catId; ?>" id="catId" />
                            <input type="hidden" id="optReg" name="optReg" value="<?php echo ($this->idToUpdate>0) ? 'update': 'new';?>" />
                            <input type="hidden" id="strTabSelected" name="strTabSelected" value="<?php echo $this->tabSelected;?>" />
                            <input type="hidden" id="inputEmpresa"   name="inputEmpresa"   value="<?php echo $this->dataUser['ID_EMPRESA'];?>" />
                            <div class="panel panel-default">
                                <div class="panel-body">                                                        
                                    <div class="form-group">
                                        <label for="inputTitulo" class="col-sm-3 control-label"><span class="mandatory">*</span> Titulo</label>
                                        <div class="col-sm-9">
                                            <input id="inputTitulo" name="inputTitulo" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['TITULO'];?>"  autocomplete="off">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputDescripcion" class="col-sm-3 control-label"><span class="mandatory">*</span> Descripción</label>
                                        <div class="col-sm-9">
                                            <input id="inputDescripcion" name="inputDescripcion" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['DESCRIPCION'];?>"  autocomplete="off">
                                        </div>
                                    </div>  

                                    <!--<div class="form-group">
                                        <label for="inputOrden" class="col-sm-3 control-label"><span class="mandatory">*</span> Orden</label>
                                        <div class="col-sm-2">
                                            <input id="inputOrden" name="inputOrden" type="text" class="input-inline form-control"  value="<?php echo @$this->aDataInfo['ORDEN'];?>"  autocomplete="off">
                                        </div>
                                    </div>      -->                                                   

                                    <div class="form-group">
                                        <label for="inputEstatus" class="col-sm-3 control-label"><span class="mandatory">*</span> Estatus</label>
                                        <div class="col-sm-2">
                                            <select id="inputEstatus" name="inputEstatus" class="">
                                                <?php echo $this->aEstatus ;?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputLocate" class="col-sm-3 control-label"><span class="mandatory">*</span> Localización</label>
                                        <div class="col-sm-2">
                                            <select id="inputLocate" name="inputLocate" class="">
                                                <?php echo $this->aLocal ;?>
                                            </select>
                                        </div>
                                    </div>                            

                                    <div class="form-group">
                                        <label for="inputPhotos" class="col-sm-3 control-label"><span class="mandatory">*</span> Fotos Extras</label>
                                        <div class="col-sm-2">
                                            <select id="inputPhotos" name="inputPhotos" class="">
                                                <?php echo $this->aFotos ;?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputQrs" class="col-sm-3 control-label"><span class="mandatory">*</span> QR Extras</label>
                                        <div class="col-sm-2">
                                            <select id="inputQrs" name="inputQrs" class="">
                                                <?php echo $this->aQrs ;?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="inputFirma" class="col-sm-3 control-label"><span class="mandatory">*</span> Firmas Extras</label>
                                        <div class="col-sm-2">
                                            <select id="inputFirma" name="inputFirma" class="">
                                                <?php echo $this->aFirms ;?>
                                            </select>
                                        </div>
                                    </div>
                                
                                    <?php if($disabled!='disabled'):?>
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <div class="pull-right">
                                                    <button type="submit" class="btn btn-info">Guardar Cambios</button>
                                                    <button type="button" class="btn default" onClick="location.href=<?php echo $this->moduleInfo['SCRIPT']; ?>';">Cancelar</button>   
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif;?>  
                                </div>
                            </div>                                                               
                        </form>
                    </div>
                </div>
            </div>
            <div id="divElementos" class="col-md-5" style="display:none;">
                <div class="widget radius-bordered">
                    <div class="widget-header bg-blue">
                        <span class="widget-caption">Elementos</span>
                    </div>
                    <div class="widget-body padding-5">
                        <div class="block">
                            <button class="btn btn-block btn-success center-text" type="button" onClick="showinfoElement(-1);"><i class="fa fa-plus-circle"></i> Agregar Elemento</button>
                        </div> 

                        <form id="formDbmanOrders" class="form-horizontal" role="form" method="POST" action="<?php echo $urlActions;?>" <?php echo ($this->DbmanInfo['INCLUYE_ARCHIVOS']==1) ? 'enctype="multipart/form-data"' :'';?>>                                
                            <input type="hidden" id="catId"          name="catId"           value="<?php echo $this->catId; ?>" id="catId" />
                            <input type="hidden" id="optReg"         name="optReg"          value="updateOrdes" />
                            <input type="hidden" id="strTabSelected" name="strTabSelected"  value="<?php echo $this->tabSelected;?>" />
                            <input type="hidden" id="inputEmpresa"   name="inputEmpresa"    value="<?php echo $this->dataUser['ID_EMPRESA'];?>" />

                            <div class="dd dd-draghandle bordered listElements">
                                <ol id="listElements" class="dd-list">
                                    <?php $controlGRal=0;?>
                                    <?php $control=1;?>
                                    <?php foreach(@$this->aElements as $key => $items):?>
                                        <li id="li_<?php echo $control;?>" class="dd-item dd2-item item1" data-id="<?php echo $control;?>">
                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][id]"         id="li_<?php echo $control;?>_id" value="<?php echo $items['ID'];?>"/>
                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][orden]"      id="li_<?php echo $control;?>_ordn" value="<?php echo $items['ORDEN'];?>"/>
                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][suborden]"   id="li_<?php echo $control;?>_subordn"  value="<?php echo $items['SUBORDEN'];?>"/>
                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][depende]"    id="li_<?php echo $control;?>_depd" value="<?php echo $items['DEPENDE'];?>"/>
                                            <div class="dd-handle dd2-handle">
                                                <span id="li_<?php echo $control;?>_span"><?php echo $control;?></span>
                                                <i class="drag-icon fa fa-arrows-alt "></i>
                                            </div>

                                            <div class="dd2-content"><?php echo $items['N_ELEMENTO'];?>
                                                <div class="pull-right"> 
                                                    <a href="javascript:showinfoElement(<?php echo $items['ID']; ?>);" class="btn btn-info btn-xs icon-only shiny white"><i class="dropdown-icon fa fa-info-circle"></i></a>
                                                    <a href="javascript:deleteElement(<?php echo $items['ID'];?>,<?php echo $this->idToUpdate;?>);" class="btn btn-danger btn-xs icon-only shiny white"><i class="dropdown-icon fa fa-times-circle"></i></a>
                                                </div>
                                            </div>
                                            <?php if(isset($items['aSubElementos'])): ?>

                                                <?php $controlInt=1;?>
                                                <ol id="innerList_<?php echo $control;?>" class="dd-list innerList" style="">
                                                    <?php foreach($items['aSubElementos'] as $key => $subItems): ?>          
                                                        <?php $controlGRal++;?>                                          
                                                        <li id="li_<?php echo $control.'_'.$controlInt;?>"  class="dd-item dd2-item item1" data-id="16">
                                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][id]"       id="li_<?php echo $control.'_'.$controlInt;?>_id"    value="<?php echo $subItems['ID'];?>"/>
                                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][orden]"    id="li_<?php echo $control.'_'.$controlInt;?>_ordn"  value="<?php echo $subItems['ORDEN'];?>"/>
                                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][suborden]" id="li_<?php echo $control.'_'.$controlInt;?>_subordn"  value="<?php echo $subItems['SUBORDEN'];?>"/>
                                                            <input type="hidden" name="aElements[<?php echo $controlGRal;?>][depende]"  id="li_<?php echo $control.'_'.$controlInt;?>_depd"  value="<?php echo $subItems['DEPENDE'];?>"/>
                                                            <div class="dd-handle dd2-handle">
                                                                <span id="li_<?php echo $control.'_'.$controlInt;?>_span"><?php echo $control."-".$controlInt;?></span>
                                                                <i class="drag-icon fa fa-arrows-alt "></i>
                                                            </div>
                                                            <div class="dd2-content"><?php echo $subItems['N_ELEMENTO'];?>
                                                                <div class="pull-right"> 
                                                                    <a href="javascript:showinfoElement(<?php echo $subItems['ID']; ?>);" class="btn btn-info btn-xs icon-only shiny white"><i class="dropdown-icon fa fa-info-circle"></i></a>
                                                                    <a href="javascript:deleteElement(<?php echo $items['ID'];?>,<?php echo $this->idToUpdate;?>);" class="btn btn-danger btn-xs icon-only shiny white"><i class="dropdown-icon fa fa-times-circle"></i></a>
                                                                </div>
                                                            </div>
                                                        </li>
                                                        <?php $controlInt++;?>
                                                    <?php endforeach;?>
                                                </ol>
                                            <?php endif;?>
                                        </li>
                                        <?php $controlGRal++;?>  
                                        <?php $control++;?>
                                    <?php endforeach;?>                                                                                                                                            
                                </ol>
                                <input type="text" id="inputCountElements" name="inputCountElements" value="<?php echo $control; ?>" style="display:none;"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    <?php endif;?>
</div>

    <!--LArge Modal Templates-->
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" id="myLargeModalEl" aria-labelledby="myLargeModalEl" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">

                <div class="modal-header">
                    <!--<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>-->
                    <h4 class="modal-title" id="myLargeModalLabel">Información del Elemento</h4>
                </div>
                <div class="modal-body">
                    <!--<img id="loader1" class="col-xs-offset-4" src="/images/loading.gif" alt="loading gif"/>-->
                    <iframe class="hmodal500" id="iFrameElement" src="" style="zoom:0" frameborder="0"  scrolling="no"></iframe>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    <!--End Large Modal Templates-->    




<!--
<div id="divSelectStatus" class="hide">
    <?php echo $this->selectStatus;?>
</div>

<div id="divSelectOptions" class="hide">
    <?php echo $this->selectOptions;?>
</div>

<div id="divSelectTipos" class="hide">
    <?php echo $this->selectTipos;?>
</div>

<div id="divSelectCats" class="hide">
    <?php echo $this->selectCatalogs;?>
</div>

<div id="divSelectReq" class="hide">
    <?php echo $this->selectReq;?>
</div>
-->
